(function(){/*

SPF
(c) 2012-2014 Google, Inc.
License: MIT
*/
function l(a,b,c){var d=Array.prototype.slice.call(arguments,2);return function(){var c=d.slice();c.push.apply(c,arguments);return a.apply(b,c)}}function aa(a,b){if(a){var c=Array.prototype.slice.call(arguments,1);try{return a.apply(null,c)}catch(d){return d}}}function m(a,b){if(document.createEvent){var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,b);return document.dispatchEvent(c)}return!0}function n(){return(new Date).getTime()};function ba(a){return a.classList?a.classList:a.className&&a.className.match(/\S+/g)||[]}function p(a,b){if(a.classList)return a.classList.contains(b);for(var c=ba(a),d=0,e=c.length;d<e;d++)if(c[d]==b)return!0;return!1}function ca(a,b){a.classList?a.classList.add(b):p(a,b)||(a.className+=" "+b)}function da(a,b){if(a.classList)a.classList.remove(b);else{for(var c=ba(a),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ")}};function ea(a,b,c,d){var e=d||{},f=!1,g=0,h,k=new XMLHttpRequest;k.open(a,b,!0);k.timing={};var q=k.abort;k.abort=function(){clearTimeout(h);k.onreadystatechange=null;q.call(k)};k.onreadystatechange=function(){var a=k.timing;if(2==k.readyState){a.responseStart=a.responseStart||n();f=-1<(k.getResponseHeader("Transfer-Encoding")||"").toLowerCase().indexOf("chunked");if(!f){var a=k.getResponseHeader("X-Firefox-Spdy"),c=window.chrome&&chrome.loadTimes&&chrome.loadTimes(),c=c&&c.wasFetchedViaSpdy;f=!(!a&&
!c)}e.v&&e.v(k)}else 3==k.readyState?f&&e.l&&(a=k.responseText.substring(g),g=k.responseText.length,e.l(k,a)):4==k.readyState&&(a.responseEnd=a.responseEnd||n(),window.performance&&window.performance.getEntriesByName&&(k.resourceTiming=window.performance.getEntriesByName(b)[0]),f&&e.l&&k.responseText.length>g&&(a=k.responseText.substring(g),g=k.responseText.length,e.l(k,a)),clearTimeout(h),e.u&&e.u(k))};a="POST"==a;if(e.headers)for(var D in e.headers)k.setRequestHeader(D,e.headers[D]),"content-type"==
D.toLowerCase()&&(a=!1);a&&k.setRequestHeader("Content-Type","application/x-www-form-urlencoded");0<e.A&&(h=setTimeout(function(){k.abort();e.w&&e.w(k)},e.A));k.timing.fetchStart=n();k.send(c);return k};function r(a,b){return s[a]=b}var s=window._spf_state||{};window._spf_state=s;function t(a,b){if(a.forEach)a.forEach(b,void 0);else for(var c=0,d=a.length;c<d;c++)c in a&&b.call(void 0,a[c],c,a)}function u(a,b){if(a.every)return a.every(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&!b.call(void 0,a[c],c,a))return!1;return!0}function fa(a,b){if(a.filter)return a.filter(b,void 0);var c=[];t(a,function(a,e,f){b.call(void 0,a,e,f)&&c.push(a)});return c}
function ga(a,b){if(a.map)return a.map(b,void 0);var c=[];c.length=a.length;t(a,function(a,e,f){c[e]=b.call(void 0,a,e,f)});return c}function v(a){return"[object Array]"==Object.prototype.toString.call(a)?a:[a]};var ha={"animation-class":"spf-animate","animation-duration":425,"cache-lifetime":6E5,"cache-max":50,"cache-unified":!1,"link-class":"spf-link","nolink-class":"spf-nolink","navigate-limit":20,"navigate-lifetime":864E5,"reload-identifier":null,"request-timeout":0,"url-identifier":"?spf=__type__"},w={};"config"in s||r("config",w);w=s.config;function ia(a,b){var c=b||document;return c.querySelectorAll?c.querySelectorAll(a):[]}function ja(a){var b,c=a.parentNode;if(c&&11!=c.nodeType)if(a.removeNode)a.removeNode(!1);else{for(;b=a.firstChild;)c.insertBefore(b,a);c.removeChild(a)}}function ka(a,b,c){for(;a;){if(b(a))return a;if(c&&a==c)break;a=a.parentNode}return null}
function la(a,b,c){a=a||"";b=b||document;var d=b.createElement("iframe");d.id=a;d.src='javascript:""';d.style.display="none";c&&(d.onload=l(c,null,d));b.body.appendChild(d);return d};function x(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function ma(a){return"[object String]"==Object.prototype.toString.call(a)}var y=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")};function na(a){a=a.split("#");return[a[0],a.slice(1).join("#")]};function oa(a){var b=z();a in b&&delete b[a]}function pa(){var a=z(),b;for(b in a)qa(a[b])||delete a[b];a=z();b=parseInt(w["cache-max"],10);b=isNaN(b)?Infinity:b;b=Object.keys(a).length-b;if(!(0>=b))for(var c=0;c<b;c++){var d=Infinity,e,f;for(f in a)a[f].count<d&&(e=f,d=a[f].count);delete a[e]}}function qa(a){if(!(a&&"data"in a))return!1;var b=a.life,b=isNaN(b)?Infinity:b;return n()-a.time<b}function ra(a){var b=parseInt(s["cache-counter"],10)||0;b++;r("cache-counter",b);a.count=b}
function z(a){return!a&&"cache-storage"in s?s["cache-storage"]:r("cache-storage",a||{})};function sa(a,b,c,d){var e=window.history.state;d&&e&&(b=b||e);ta(!0,a,b,c)}function ta(a,b,c,d){if(b||c){b=b||window.location.href;c=c||{};var e=n();r("history-timestamp",e);c["spf-timestamp"]=e;if(a)ua(c,b);else if(a=va().contentWindow.history.pushState,"function"==typeof a)a.call(window.history,c,"",b);else throw Error("history.pushState is not a function.");r("history-url",b);d&&(d=s["history-callback"])&&d(b,c)}}
function wa(a){var b=window.location.href;if(s["history-ignore-pop"])r("history-ignore-pop",!1);else if(a.state){a=a.state;var c=a["spf-timestamp"];b==s["history-url"]?(r("history-timestamp",c),ua(a,b)):(a["spf-back"]=c<parseInt(s["history-timestamp"],10),a["spf-current"]=s["history-url"],r("history-timestamp",c),r("history-url",b),(c=s["history-callback"])&&c(b,a))}}
function ua(a,b){var c=va().contentWindow.history.replaceState;if("function"==typeof c)c.call(window.history,a,"",b);else throw Error("history.replaceState is not a function");}function va(){var a=document.getElementById("history-iframe");a||(a=la("history-iframe"));return a};function xa(a,b){a&&b&&(a in A||(A[a]=[]),A[a].push(b))}function ya(a,b){a in A&&b&&u(A[a],function(a,d,e){return a==b?(e[d]=null,!1):!0})}function za(a){a in A&&t(A[a],function(a,c,d){d[c]=null;a&&a()})}var A={};"ps-s"in s||r("ps-s",A);A=s["ps-s"];function B(a,b,c){var d=C[a];return a&&b?(d||(d=C[a]={items:[],k:0,n:1}),d.items.push({F:b,D:c||0})):d&&d.items.length||0}function E(a,b){var c=C[a];if(c){var d=0<c.k;0<c.n&&(b||!d)&&Aa(a,b)}}function F(a){(a=C[a])&&a.n--}function G(a,b){var c=C[a];c&&(c.n++,E(a,b))}function Ba(a){var b=C[a];b&&(clearTimeout(b.k),delete C[a])}function Ca(a){var b=parseInt(s.uid,10)||0;b++;return a["spf-key"]||(a["spf-key"]=""+r("uid",b))}
function Aa(a,b){var c=C[a];if(c&&(clearTimeout(c.k),c.k=0,0<c.n)){var d=c.items.shift();if(d){var e=l(function(a,b){a();b()},null,d.F,l(Aa,null,a,b));b?e():c.k=setTimeout(e,d.D)}}}var C={};function H(a){var b=document.createElement("a");b.href=a;b.href=b.href;a={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,H:b.H,G:b.G};a.origin=a.protocol+"//"+a.host;a.pathname&&"/"==a.pathname[0]||(a.pathname="/"+a.pathname);return a}function I(a){a=H(a);return na(a.href)[0]}
function Da(a,b){var c=Ea(a);a=c[0];for(var d=0;d<b.length;d++)a=a.replace(new RegExp("([?&])"+b[d]+"(?:=[^&]*)?(?:(?=[&])|$)","g"),function(a,b){return"?"==b?b:""});x(a,"?")&&(a=a.slice(0,-1));return a+c[1]}function Ea(a){var b="";-1!=a.indexOf("#")&&(b=na(a),a=b[0],b="#"+b[1]);return[a,b]};function Fa(a,b,c,d){var e="js"==a;b=v(b);var f=ma(c),g=f?c:"",h=f?d:c;b=ga(b,l(J,null,a));c=h;if(g){d=u(b,l(Ga,null,a));var k=K[a+"-"+g],k=k&&fa(k,function(a){n:if(b.indexOf)a=b.indexOf(a,void 0);else{for(var c=0;c<b.length;c++)if(c in b&&b[c]===a){a=c;break n}a=-1}return-1==a});!d&&k&&k.length&&(m(e?"spfjsbeforeunload":"spfcssbeforeunload",{name:g,urls:k}),delete K[a+"-"+g],c=function(){Ha(a,g,k);h&&h()})}e=g||"^"+b.sort().join("^");K[a+"-"+e]=b;xa(a+"-"+e,c);t(b,function(b){L[a+"-"+b]?Ia(a):(b=
M(a,b,l(Ia,null,a)))&&g&&b.setAttribute("name",g)})}function Ja(a,b){var c=K[a+"-"+b]||[];delete K[a+"-"+b];Ha(a,b,c)}function Ha(a,b,c){c.length&&(m("js"==a?"spfjsunload":"spfcssunload",{name:b,urls:c}),t(c,function(b){Ka(a,b)}))}function Ia(a){var b=a+"-",c;for(c in A)0==c.indexOf(b)&&u(c.substring(b.length).split("|"),l(La,null,a))&&za(c)}
function M(a,b,c,d){function e(){L[a+"-"+b]&&(L[a+"-"+b]=2);f&&h&&h.parentNode&&g==document&&h.parentNode.removeChild(h);c&&setTimeout(c,0);return null}var f="js"==a;b=J(a,b);L[a+"-"+b]=1;var g=d||document,h=g.createElement(f?"script":"link");if(!b)return e();d=N(b);h.className=a+"-"+d;"onload"in h?h.onerror=h.onload=e:h.onreadystatechange=function(){/^c|loade/.test(h.readyState)&&e()};d=g.getElementsByTagName("head")[0];f?(h.async=!0,h.src=b,d.insertBefore(h,d.firstChild)):(h.rel="stylesheet",h.href=
b,d.appendChild(h));return h}function Ka(a,b){b=J(a,b);var c=N(b),c=ia("."+(a+"-"+c),void 0);t(c,function(a){a&&a.parentNode&&a.parentNode.removeChild(a)});delete L[a+"-"+b]}function Ma(a){var b="js"==a,c=[];t(ia(b?"script[src]":'link[rel~="stylesheet"]'),function(d){var e=b?d.src:d.href,e=J(a,e);if(!L[a+"-"+e]){L[a+"-"+e]=2;var f=N(e);ca(d,a+"-"+f);(f=d.getAttribute("name"))&&(K[a+"-"+f]=[e]);c.push(d)}})}
function Na(a,b){if(b&&(b=J(a,b),!L[a+"-"+b])){var c=N(b),d=a+"-"+c,e=a+"-prefetch",c=document.getElementById(e);if(!c)c=la(e,null,function(a){a.title=e;E(e,!0)});else if(c.contentWindow.document.getElementById(d))return;d=l(Oa,null,c,a,b,d);c.title?d():B(e,d)}}function Oa(a,b,c,d){a=a.contentWindow.document;"js"==b?(b=a.createElement("object"),Pa?a.createElement("script").src=c:b.data=c,b.id=d,a.body.appendChild(b)):(b=M(b,c,null,a),b.id=d)}
function Qa(a,b,c){for(var d="js"==a,e=K[a+"-"+c],f=b.replace(/\s/g,""),f=f||"",g=0,h=0,k=f.length;h<k;++h)g=31*g+f.charCodeAt(h),g%=4294967296;f="hash-"+g;K[a+"-"+c]=[f];!Ga(a,f)&&(b=O(a,b))&&(L[a+"-"+f]=2,b&&!d&&(d=N(f),b.className=a+"-"+d,b.setAttribute("name",c)),(e=e&&e[0])&&Ka(a,e))}
function O(a,b){b=y(b);if(!b)return null;var c=document.getElementsByTagName("head")[0]||document.body,d;"js"==a?(d=document.createElement("script"),d.text=b,c.appendChild(d),c.removeChild(d)):(d=document.createElement("style"),c.appendChild(d),"styleSheet"in d?d.styleSheet.cssText=b:d.appendChild(document.createTextNode(b)));return d}
function J(a,b){var c="rsrc-p-"+a;if(b){var d=b.indexOf("//");if(0>d){if(0==b.lastIndexOf("hash-",0))return b;c=s[c]||"";if(ma(c))b=c+b;else for(var e in c)b=b.replace(e,c[e]);b=0>b.indexOf("."+a)?b+"."+a:b;b=I(b)}else 0==d&&(b=I(b))}return b}function Ra(a){return"js-"+a}function N(a){return a?String(a).replace(/[^\w]/g,""):""}function Ga(a,b){return 2==L[a+"-"+b]}function La(a,b){var c=K[a+"-"+b],d=l(Ga,null,a);return!b||!!c&&u(c,d)}var L={},K={},Pa=-1!=navigator.userAgent.indexOf(" Trident/");
"rsrc-s"in s||r("rsrc-s",L);L=s["rsrc-s"];"rsrc-u"in s||r("rsrc-u",K);K=s["rsrc-u"];function P(a,b,c){Fa("js",a,b,c)}function Sa(a){Ja("js",a)}function Ta(a,b){M("js",a,b)}function Ua(a){a=v(a);t(a,function(a){Na("js",a)})}function Va(a,b,c){a=v(a);var d=[];t(a,function(a){a&&!K["js-"+a]&&d.push(a)});var e=!d.length;if(b){var f=u(a,l(La,null,"js"));e&&f?b():(a=Ra(a.sort().join("|")),xa(a,b))}c&&!e&&c(d)}function Wa(a,b){a=v(a);t(a,function(a){a&&Xa(a,Q[a]||a)&&Ya(a)});Va(a,b,Za)}function Za(a){t(a,function(a){function c(){P(e,a)}var d=R[a],e=Q[a]||a;d?Wa(d,c):c()})}
function Ya(a){a=v(a);t(a,function(a){var c=[],d;for(d in R){var e=R[d],e=v(e);t(e,function(e){e==a&&c.push(d)})}t(c,function(a){Ya(a)});Sa(a)})}function $a(a,b){Qa("js",a,b)}function ab(a){O("js",a)}function Xa(a,b){var c=K["js-"+a];return c?(b=v(b),!u(c,function(a,e){return c[e]==J("js",b[e])})):!1}var R={};"js-d"in s||r("js-d",R);var R=s["js-d"],Q={};"js-u"in s||r("js-u",Q);Q=s["js-u"];function bb(a,b,c){Fa("css",a,b,c)}function cb(a,b){M("css",a,b)}function db(a){a=v(a);t(a,function(a){Na("css",a)})};function eb(a,b,c){if(b){var d=[],e;b=0;c&&(a+="\r\n");var f=a.indexOf("[\r\n",b);for(-1<f&&(b=f+3);-1<(f=a.indexOf(",\r\n",b));)e=y(a.substring(b,f)),b=f+3,e&&d.push(JSON.parse(e));f=a.indexOf("]\r\n",b);-1<f&&(e=y(a.substring(b,f)),b=f+3,e&&d.push(JSON.parse(e)));e="";a.length>b&&(e=a.substring(b),c&&x(e,"\r\n")&&(e=e.substring(0,e.length-2)));return{j:d,a:e}}a=JSON.parse(a);"number"==typeof a.length?d=a:d=[a];return{j:d,a:""}}
function S(a,b,c,d,e){var f="process "+I(a),g=!w["experimental-process-async"],h;h=0;b.timing||(b.timing={});b.title&&(document.title=b.title);d&&b.url&&I(b.url)!=I(window.location.href)&&sa(b.url+window.location.hash,null,!1,!0);b.head&&(h=l(function(a,b){var c=T(a);U(c);F(f);fb(c,function(){b.spfProcessHead=n();G(f,g)})},null,b.head,b.timing),h=B(f,h));b.attr&&(h=l(function(a,b){for(var c in a){var d=document.getElementById(c);if(d){var e=a[c],f=void 0;for(f in e){var g=e[f];"class"==f?d.className=
g:"style"==f?d.style.cssText=g:d.setAttribute(f,g)}}}b.spfProcessAttr=n()},null,b.attr,b.timing),h=B(f,h));d=b.body||{};var k=h,q;for(q in d)h=l(function(a,b){var c=document.getElementById(a);if(c){var d=T(b),h=w["animation-class"];if(gb&&p(c,h)){F(f);var k=Ca(c);E(k,!0);h={p:d,reverse:!!e,f:null,h:null,g:c,B:h+"-old",C:h+"-new",t:e?h+"-reverse-start":h+"-forward-start",s:e?h+"-reverse-end":h+"-forward-end"};c=l(function(a){U(a.p);ca(a.g,a.t);a.f=document.createElement("div");a.f.className=a.B;var b=
a.g,c=a.f;if(c){for(var d;d=b.firstChild;)c.appendChild(d);b.appendChild(c)}a.h=document.createElement("div");a.h.className=a.C;a.h.innerHTML=a.p.i;a.reverse?(b=a.f,b.parentNode.insertBefore(a.h,b)):(b=a.f,b.parentNode.insertBefore(a.h,b.nextSibling))},null,h);B(k,c,0);c=l(function(a){da(a.g,a.t);ca(a.g,a.s)},null,h);B(k,c,0);c=l(function(a){a.g.removeChild(a.f);da(a.g,a.s);ja(a.h);F(k);fb(a.p,function(){G(k)})},null,h);B(k,c,parseInt(w["animation-duration"],10));c=l(function(a,b){G(b)},null,h,f);
B(k,c);E(k)}else{U(d);var q=function(){F(f);fb(d,function(){G(f,g)})};(h=w["experimental-html-handler"])?(F(f),h(d.i,c,function(){q();G(f,g)})):(c.innerHTML=d.i,q())}}},null,q,d[q],b.timing),h=B(f,h);q=h-k;b.foot?(h=l(function(a,b,c){c&&(b.spfProcessBody=n());a=T(a);U(a);F(f);fb(a,function(){b.spfProcessFoot=n();G(f,g)})},null,b.foot,b.timing,q),h=B(f,h)):q&&(h=l(function(a){a.spfProcessBody=n()},null,b.timing),h=B(f,h));c&&(h=B(f,l(c,null,a,b)));E(f,g)}
function hb(a,b,c){var d="preprocess "+I(a),e;b.head&&(e=l(function(a){a=T(a);ib(a);jb(a)},null,b.head),B(d,e));var f=b.body||{},g;for(g in f)f[g]&&(e=l(function(a,b){var c=T(b);ib(c);jb(c)},null,g,f[g]),B(d,e));b.foot&&(e=l(function(a){a=T(a);ib(a);jb(a)},null,b.foot),B(d,e));c&&B(d,l(c,null,a,b));E(d)}
function T(a){var b=new kb;if(!a)return b;if(!ma(a))return a.scripts&&t(a.scripts,function(a){b.d.push({url:a.url||"",text:a.text||"",name:a.name||"",async:a.async||!1})}),a.styles&&t(a.styles,function(a){b.c.push({url:a.url||"",text:a.text||"",name:a.name||""})}),b.i=a.html||"",b;a=a.replace(lb,function(a,d,e,f){return"script"==d?(a=(a=e.match(mb))?a[1]:"",d=(d=e.match(nb))?d[1]:"",e=ob.test(e),b.d.push({url:d,text:f,name:a,async:e}),""):"style"==d?(a=(a=e.match(mb))?a[1]:"",b.c.push({url:"",text:f,
name:a}),""):a});a=a.replace(pb,function(a,d){var e=d.match(qb),e=e?e[1]:"";if("stylesheet"==e){var e=(e=d.match(mb))?e[1]:"",f=d.match(rb),f=f?f[1]:"";b.c.push({url:f,text:"",name:e});return""}return a});b.i=a;return b}
function fb(a,b){if(0>=a.d.length)b&&b();else{var c=-1,d=function(){c++;if(c<a.d.length){var e=a.d[c],f=function(){};e.url?f=w["experimental-execute-unified"]?e.name?l(P,null,e.url,e.name):l(Ta,null,e.url):l(P,null,e.url,e.name):e.text&&(f=w["experimental-execute-unified"]?e.name?l($a,null,e.text,e.name):l(ab,null,e.text):l(ab,null,e.text));e.url&&!e.async?f(d):(f(),d())}else b&&b()};d()}}function jb(a){0>=a.d.length||(a=ga(a.d,function(a){return a.url}),Ua(a))}
function U(a){if(!(0>=a.c.length))for(var b=0,c=a.c.length;b<c;b++){var d=a.c[b];d.url?w["experimental-execute-unified"]?d.name?bb(d.url,d.name):cb(d.url):bb(d.url,d.name):d.text&&(w["experimental-execute-unified"]?d.name?Qa("css",d.text,d.name):O("css",d.text):O("css",d.text))}}function ib(a){0>=a.c.length||(a=ga(a.c,function(a){return a.url}),db(a))}function kb(){this.i="";this.d=[];this.c=[]}
var gb=function(){var a=document.createElement("div");if("transition"in a.style)return!0;for(var b=["webkit","Moz","Ms","O","Khtml"],c=0,d=b.length;c<d;c++)if(b[c]+"Transition"in a.style)return!0;return!1}(),pb=/\x3clink([\s\S]*?)\x3e/ig,lb=/\x3c(script|style)([\s\S]*?)\x3e([\s\S]*?)\x3c\/\1\x3e/ig,ob=/(?:\s|^)async(?:\s|=|$)/i,rb=/(?:\s|^)href\s*=\s*["']?([^\s"']+)/i,mb=/(?:\s|^)name\s*=\s*["']?([^\s"']+)/i,qb=/(?:\s|^)rel\s*=\s*["']?([^\s"']+)/i,nb=/(?:\s|^)src\s*=\s*["']?([^\s"']+)/i;function sb(a,b){var c=b||{};c.method=((c.method||"GET")+"").toUpperCase();c.type=c.type||"request";var d=a,e=w["url-identifier"]||"";if(e){var e=e.replace("__type__",c.type||""),f=Ea(d),d=f[0];0==e.lastIndexOf("?",0)&&-1!=d.indexOf("?")&&(e=e.replace("?","&"));d+=e+f[1]}d=I(d);e={};e.spfUrl=d;e.startTime=n();e.fetchStart=e.startTime;n:{var g=tb(a,c.current,null,c.type,!1),h=c.current,f=[];h&&(f.push(g+" previous "+h),f.push(g+" previous "+H(h).pathname));f.push(g);g=0;for(h=f.length;g<h;g++){var k;
r:{k=f[g];var q=z();if(k in q){q=q[k];if(qa(q)){ra(q);k=q.data;break r}oa(k)}k=void 0}if(k){f={key:f[g],response:k.response,type:k.type};break n}}f=null}e.spfPrefetched=!!f&&"prefetch"==f.type;e.spfCached=!!f;if(f)return setTimeout(l(ub,null,a,c,e,f.key,f.response),0),null;f={};void 0!=c.r&&(f["X-SPF-Referer"]=c.r);c.current&&(f["X-SPF-Previous"]=c.current);g={q:!1,a:"",complete:[]};e=l(vb,null,a,c,e,g);e={headers:f,A:w["request-timeout"],v:l(wb,null,a,g),l:l(xb,null,a,c,g),u:e,w:e};return"POST"==
c.method?ea("POST",d,c.o,e):ea("GET",d,null,e)}function ub(a,b,c,d,e){var f=!1;c.responseStart=c.responseEnd=n();b.type&&0==b.type.lastIndexOf("navigate",0)&&(c.navigationStart=c.startTime,w["cache-unified"]||(oa(d),f=!0));if(b.b&&"multipart"==e.type){d=e.parts;for(var g=0;g<d.length;g++)b.b(a,d[g])}yb(a,b,c,e,f)}function wb(a,b,c){a=c.getResponseHeader("X-SPF-Response-Type")||"";b.q=-1!=a.toLowerCase().indexOf("multipart")}
function xb(a,b,c,d,e,f){if(c.q){e=c.a+e;var g;try{g=eb(e,!0,f)}catch(h){d.abort();b.e&&b.e(a,h);return}if(b.b)for(d=0;d<g.j.length;d++)b.b(a,g.j[d]);c.complete=c.complete.concat(g.j);c.a=g.a}}
function vb(a,b,c,d,e){if(e.timing)for(var f in e.timing)c[f]=e.timing[f];if(e.resourceTiming)if("load"==b.type)for(var g in e.resourceTiming)c[g]=e.resourceTiming[g];else if(window.performance&&window.performance.timing){f=window.performance.timing.navigationStart;for(var h in e.resourceTiming)g=e.resourceTiming[h],void 0!==g&&(x(h,"Start")||x(h,"End")||"startTime"==h)&&(c[h]=f+Math.round(g))}"load"!=b.type&&(c.navigationStart=c.startTime);d.complete.length&&(d.a=y(d.a),d.a&&xb(a,b,d,e,"",!0));var k;
try{k=eb(e.responseText).j}catch(q){b.e&&b.e(a,q);return}if(b.b&&1<k.length)for(d=d.complete.length;d<k.length;d++)b.b(a,k[d]);if(1<k.length){var D;d=0;for(e=k.length;d<e;d++)h=k[d],h.cacheType&&(D=h.cacheType);k={parts:k,type:"multipart"};D&&(k.cacheType=D)}else k=1==k.length?k[0]:{};yb(a,b,c,k,!0)}
function yb(a,b,c,d,e){if(e&&"POST"!=b.method&&(e=tb(a,b.current,d.cacheType,b.type,!0))){d.cacheKey=e;var f={response:d,type:b.type||""},g=parseInt(w["cache-lifetime"],10),h=parseInt(w["cache-max"],10);0>=g||0>=h||(h=z(),f={data:f,life:g,time:n(),count:0},ra(f),h[e]=f,setTimeout(pa,1E3))}d.timing=c;b.m&&b.m(a,d)}
function tb(a,b,c,d,e){a=I(a);var f;w["cache-unified"]?f=a:"navigate-back"==d||"navigate-forward"==d?f="history "+a:"navigate"==d?f=(e?"history ":"prefetch ")+a:"prefetch"==d&&(f=e?"prefetch "+a:"");b&&"url"==c?f+=" previous "+b:b&&"path"==c&&(f+=" previous "+H(b).pathname);return f||""};function zb(a){return ka(a,function(a){return p(a,w["link-class"])})}function Ab(a){return ka(a,function(a){return p(a,w["nolink-class"])})}function Bb(a,b){return ka(a,function(a){return a.href&&"img"!=a.tagName.toLowerCase()},b)}function Cb(a){if(a.metaKey||a.altKey||a.ctrlKey||a.shiftKey||0<a.button)return null;var b=zb(a.target);return!b||w["nolink-class"]&&Ab(a.target)?null:(a=Bb(a.target,b))?a.href:null}function Db(a){return H(a).origin!=H(window.location.href).origin?!1:!0}
function Eb(){if(!s["nav-init"])return!1;var a=parseInt(s["nav-counter"],10)||0;a++;var b=parseInt(w["navigate-limit"],10),b=isNaN(b)?Infinity:b;if(a>b)return!1;a=w["experimental-init-lifetime"]?parseInt(s["nav-init-time"],10):parseInt(s["nav-time"],10);a--;a=n()-a;b=parseInt(w["navigate-lifetime"],10);b=isNaN(b)?Infinity:b;return a>b?!1:!0}
function Fb(a){if(!a.defaultPrevented){var b=Cb(a);null!==b&&(b&&b!=window.location.href?(!w["experimental-same-origin"]||Db(b))&&Eb()&&m("spfclick",{url:b,target:a.target})&&(Gb(b),a.preventDefault()):a.preventDefault())}}function Hb(a){var b=Cb(a);b&&b!=window.location.href&&setTimeout(function(){Ib(b,void 0)},0)}
function Jb(a,b){var c=!(!b||!b["spf-back"]),d=b&&b["spf-referer"],e=b&&b["spf-current"],f=w["reload-identifier"];f&&(a=Da(a,[f]));w["experimental-same-origin"]&&!Db(a)?V(a,"9"):Eb()?m("spfhistory",{url:a,referer:d,previous:e})&&Gb(a,null,e,d,!0,c):V(a,"1")}
function Gb(a,b,c,d,e,f){b=b||{};r("nav-counter",(parseInt(s["nav-counter"],10)||0)+1);r("nav-time",n());d=void 0==d?window.location.href:d;r("nav-referer",d);c=e?c:window.location.href;if(Kb(a,d,c,b)){W();Lb(a);var g=I(a),h="preprocess "+I(g),k;for(k in C)h!=k&&0==k.lastIndexOf("preprocess",0)&&Ba(k);k=Mb()[g];r("nav-request",k);r("nav-promote",null);r("nav-promote-time",null);k&&4!=k.readyState?(f=!!e,e="preprocess "+I(a),c="promote "+I(a),r("nav-promote",a),r("nav-promote-time",n()),Ba(e),E(c,
!0),f||Nb(a,d,l(X,null,b))):(e=!!e,k=!!f,f=l(X,null,b),b=sb(a,{method:b.method,b:l(Ob,null,b,k),e:f,m:l(Pb,null,b,k,""),o:b.postData,type:"navigate"+(e?k?"-back":"-forward":""),current:c,r:d}),r("nav-request",b),e||Nb(a,d,f))}else V(a,"2")}function Nb(a,b,c){try{ta(!1,a,{"spf-referer":b},void 0)}catch(d){W(),c(a,d)}}function X(a,b,c){r("nav-request",null);Qb(b,c,a)&&(a="10",c&&(a+=" Message: "+c.message),V(b,a))}
function Ob(a,b,c,d){if(Rb(c,d,a))if(d.reload)V(c,"5");else if(d.redirect)Sb(a,d.redirect);else try{S(c,d,function(){Tb(c,d,a)},!0,b)}catch(e){X(a,c,e)}else V(c,"3")}
function Pb(a,b,c,d,e){r("nav-request",null);s["nav-promote"]==c&&(c=e.timing||{},c.navigationStart=s["nav-promote-time"],c.spfPrefetched=!0);c="multipart"==e.type;if(!c){if(!Ub(d,e,a)){V(d,"4");return}if(e.reload){V(d,"5");return}if(e.redirect){Sb(a,e.redirect);return}}try{S(d,c?{}:e,function(){var b=na(d);b[1]&&(b=document.getElementById(b[1]))&&b.scrollIntoView();Vb(d,e,a)},!0,b)}catch(f){X(a,d,f)}}function Sb(a,b){try{b+=window.location.hash,sa(b,null,!0,!0)}catch(c){W(),X(a,b,c)}}
function W(){var a=s["nav-request"];a&&(a.abort(),r("nav-request",null))}function Y(a,b){var c;a&&(c=Array.prototype.slice.call(arguments),c[0]=a,c=aa.apply(null,c));return!1!==c}
function V(a,b){W();Lb();m("spfreload",{url:a,reason:b});w["experimental-remove-history"]&&window.location.href==a&&(r("history-ignore-pop",!0),window.history.back());setTimeout(function(){var c=w["reload-identifier"];if(c){var d={};d[c]=encodeURIComponent(b);var c=a,e=Ea(c),c=e[0],f=-1!=c.indexOf("?")?"&":"?",g;for(g in d)c+=f+g,d[g]&&(c+="="+d[g]),f="&";a=c+e[1]}window.location.href=a},0)}
function Wb(a,b,c){b=b||{};c=c||a;Kb(a,void 0,void 0,b,!0)&&sb(a,{method:b.method,b:l(Xb,null,!1,b,c),e:l(Yb,null,!1,b,c),m:l(Zb,null,!1,b,c),o:b.postData,type:"load"})}function Ib(a,b,c){b=b||{};c=c||a;var d=window.location.href;Kb(a,void 0,void 0,b,!0)&&(b=sb(a,{method:b.method,b:l(Xb,null,!0,b,c),e:l(Yb,null,!0,b,c),m:l(Zb,null,!0,b,c),o:b.postData,type:"prefetch",current:d}),a=I(a),Mb()[a]=b)}function Yb(a,b,c,d,e){a&&$b(d);a&&s["nav-promote"]==c?X(b,d,e):Qb(d,e,b,!0)}
function Xb(a,b,c,d,e){if(Rb(d,e,b,!0)){if(e.reload){if(!a)return;if(s["nav-promote"]==c){V(d,"5");return}}if(e.redirect)ac(a,b,c,e.redirect);else{if(a){var f=l(Ob,null,b,!1,d,e),g="promote "+I(c);B(g,f);if(s["nav-promote"]==c){E(g,!0);return}}(a?hb:S)(d,e,function(){Tb(d,e,b,!0)})}}}
function Zb(a,b,c,d,e){var f="multipart"==e.type;if(!f){if(!Ub(d,e,b,!0)){V(d,"4");return}if(e.reload){if(!a)return;if(s["nav-promote"]==c){V(d,"5");return}}if(e.redirect){ac(a,b,c,e.redirect);return}}var g="promote "+I(c);if(a){$b(d);if(s["nav-promote"]==c){B(g,l(Pb,null,b,!1,c,d,e));E(g,!0);return}Ba(g)}g=a?hb:S;try{g(d,f?{}:e,function(){Vb(d,e,b,!0)})}catch(h){Yb(a,b,c,d,h)}}
function ac(a,b,c,d){a=a?Ib:Wb;var e={};t("onError onRequest onPartProcess onPartDone onProcess onDone".split(" "),function(a){e[a]=b[a]});a(d,e,c)}function Qb(a,b,c,d){a={url:a,err:b};(c=Y((c||{}).onError,a))&&!d&&(c=m("spferror",a));return c}function Kb(a,b,c,d,e){a={url:a,referer:b,previous:c};(d=Y((d||{}).onRequest,a))&&!e&&(d=m("spfrequest",a));return d}function Rb(a,b,c,d){a={url:a,part:b};(c=Y((c||{}).onPartProcess,a))&&!d&&(c=m("spfpartprocess",a));return c}
function Tb(a,b,c,d){a={url:a,part:b};Y((c||{}).onPartDone,a)&&!d&&m("spfpartdone",a)}function Ub(a,b,c,d){a={url:a,response:b};(c=Y((c||{}).onProcess,a))&&!d&&(c=m("spfprocess",a));return c}function Vb(a,b,c,d){a={url:a,response:b};Y((c||{}).onDone,a)&&!d&&m("spfdone",a)}function $b(a){a=I(a);var b=Mb(),c=b[a];c&&c.abort();delete b[a]}function Lb(a){var b=Mb();a=a&&I(a);for(var c in b)a!=c&&$b(c)}function Mb(){return"nav-prefetches"in s?s["nav-prefetches"]:r("nav-prefetches",{})};function Z(){Ma("js");Ma("css");"complete"==document.readyState&&(document.removeEventListener?document.removeEventListener("DOMContentLoaded",Z,!1):document.detachEvent&&document.detachEvent("onreadystatechange",Z))}document.addEventListener?document.addEventListener("DOMContentLoaded",Z,!1):document.attachEvent&&document.attachEvent("onreadystatechange",Z);Z();
var bc={init:function(a){var b=!("function"!=typeof window.history.pushState&&!va().contentWindow.history.pushState);a=a||{};for(var c in ha)w[c]=c in a?a[c]:ha[c];for(c in a)c in ha||(w[c]=a[c]);if(b){c=Qb;if(!s["history-init"]&&window.addEventListener){a=window.location.href;window.addEventListener("popstate",wa,!1);r("history-init",!0);r("history-callback",Jb);r("history-error-callback",c);r("history-listener",wa);r("history-url",a);r("history-timestamp",n());var d={"spf-referer":document.referrer};
try{sa(a,d)}catch(e){c&&c(a,e)}}!s["nav-init"]&&document.addEventListener&&(document.addEventListener("click",Fb,!1),!w["experimental-prefetch-mousedown"]||"ontouchstart"in window||0<window.navigator.maxTouchPoints||0<window.navigator.msMaxTouchPoints||(document.addEventListener("mousedown",Hb,!1),r("prefetch-listener",Hb)),r("nav-init",!0),r("nav-init-time",n()),r("nav-counter",0),r("nav-time",n()),r("nav-listener",Fb))}return b},dispose:function(){"undefined"!=typeof History&&History.prototype.pushState&&
(W(),s["nav-init"]&&(document.removeEventListener&&(document.removeEventListener("click",s["nav-listener"],!1),w["experimental-prefetch-mousedown"]&&document.removeEventListener("mousedown",s["prefetch-listener"],!1)),r("nav-init",!1),r("nav-init-time",null),r("nav-counter",null),r("nav-time",null),r("nav-listener",null)),s["history-init"]&&(window.removeEventListener&&window.removeEventListener("popstate",s["history-listener"],!1),r("history-init",!1),r("history-callback",null),r("history-error-callback",
null),r("history-listener",null),r("history-url",null),r("history-timestamp",0)));for(var a in w)delete w[a]},navigate:function(a,b){a&&a!=window.location.href&&(w["experimental-same-origin"]&&!Db(a)?V(a,"9"):Eb()?Gb(a,b):V(a,"1"))},load:function(a,b){Wb(a,b)},prefetch:function(a,b){Ib(a,b)},process:function(a,b){function c(a,c,d,e){a==c&&b&&b(e)}var d=window.location.href;if("multipart"==a.type)for(var e=a.parts,f=0;f<e.length;f++){var g=l(c,null,f,e.length-1);S(d,e[f],g)}else g=l(c,null,0,0),S(d,
a,g)}},cc={cache:{remove:oa,clear:function(){z({})}},script:{load:P,get:Ta,ready:Va,done:function(a){K["js-"+a]=[];Ia("js")},require:Wa,declare:function(a,b){if(a){for(var c in a)R[c]=a[c];if(b)for(c in b)Q[c]=b[c]}},path:function(a){r("rsrc-p-js",a)},unload:Sa,ignore:function(a,b){a=v(a);var c=Ra(a.sort().join("|"));ya(c,b)},unrequire:Ya,prefetch:Ua},style:{load:bb,get:cb,unload:function(a){Ja("css",a)},path:function(a){r("rsrc-p-css",a)},prefetch:db}},dc=this.spf=this.spf||{},ec;
for(ec in bc)dc[ec]=bc[ec];for(var $ in cc)for(var fc in cc[$])dc[$]=dc[$]||{},dc[$][fc]=cc[$][fc];m("spfready");})();
