(function(o,g){var b=o.ue_err_chan||"jserr",k="FATAL",h="v5",d=20,q=256,m=/\(?([^\s]*):(\d+):\d+\)?/,p=/.*@(.*):(\d*)/;
function n(r){if(r){return r.replace(/^\s+|\s+$/g,"");
}}function c(t){if(!t||!t.s){return;
}var u,r=t.s.length>0?t.s[0]:"",s=t.s.length>1?t.s[1]:"";
if(r){u=r.match(p);
}if((!u||u.length!=3)&&s){u=s.match(m);
}if(u&&u.length==3){t.f=u[1];
t.l=u[2];
}}function a(s,y){if(!s){return{};
}if(s.m&&s.m.message){s=s.m;
}var t={m:e(s,y),f:(s.f||s.sourceURL||s.fileName||s.filename||(s.m&&s.m.target&&s.m.target.src)),l:(s.l||s.line||s.lineno||s.lineNumber),c:s.c?""+s.c:s.c,s:[],name:s.name,type:s.type,csm:h+" "+(s.fromOnError?"onerror":"ueLogError")},x,w,r,A,u=0,v=0,B,z;
x=s.stack||(s.err?s.err.stack:"");
t.pageURL=y.pageURL||(""+(window.location?window.location.href:""))||"missing";
t.logLevel=y.logLevel||k;
z=y.attribution;
if(z){t.attribution=""+z;
}if(x&&x.split){t.csm+=" stack";
w=x.split("\n");
while(u<w.length&&t.s.length<d){r=w[u++];
if(r){t.s.push(n(r));
}}}else{t.csm+=" callee";
A=j(s.args||arguments,"callee");
u=0;
v=0;
while(A&&u<d){B=q;
if(!A.skipTrace){r=A.toString();
if(r&&r.substr){B=(v===0?4*q:B);
B=(v==1?2*q:B);
t.s.push(r.substr(0,B));
v++;
}}A=j(A,"caller");
u++;
}}if(!t.f&&t.s.length>0){c(t);
}return t;
}function e(r,t){var s=t.m||t.message||"";
if(r.m&&r.m.message){s+=r.m.message;
}else{if(r.m&&r.m.target&&r.m.target.tagName){s+="Error handler invoked by "+r.m.target.tagName+" tag";
}else{if(r.m){s+=r.m;
}else{if(r.message){s+=r.message;
}else{s+="Unknown error";
}}}}return s;
}function j(s,t){try{return s[t];
}catch(r){return;
}}function i(r,u){if(r){var t=a(r,u);
o.ue.log(t,u.channel||b,{n:1});
try{l(t);
}catch(s){}}}function l(u){var t=g.console,v=g.JSON,r="Error logged: ";
if(!t){return;
}if(v&&v.stringify){try{r+=v.stringify(u);
}catch(s){r+="no info provided; converting to string failed";
}}else{r+=u.m;
}if(typeof t.error==="function"){t.error(r,u);
}else{if(typeof t.log==="function"){t.log(r,u);
}}}function f(s,r){if((!s)||(o.ue_err.ec>o.ue_err.mxe)){return;
}o.ue_err.ec++;
o.ue_err.ter.push(s);
r=r||{};
var t=s.logLevel||r.logLevel;
r.logLevel=t;
r.attribution=s.attribution||r.attribution;
if(!t||(t==k)){ue_err.ecf++;
}i(s,r);
}i.skipTrace=1;
a.skipTrace=1;
f.skipTrace=1;
(function(){if(!o.ue_err.erl){return;
}var t=o.ue_err.erl.length,r,s;
for(r=0;
r<t;
r++){s=o.ue_err.erl[r];
i(s.ex,s.info);
}ue_err.erl=[];
})();
o.ueLogError=f;
})(ue_csm,window);
(function(aJ,am){var aU,aO,aP=aJ.uex,aK=aJ.uet,ay="ue_frst";
aJ.ue.sid=aJ.ue_sid;
aJ.ue.mid=aJ.ue_mid;
aJ.ue.furl=aJ.ue_furl;
aJ.ue.sn=aJ.ue_sn;
if(aK){aK("bb",ay,{wb:1});
}var aU={};
(function(){function g(j){return j<10?"0"+j:j;
}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(j){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+g(this.getUTCMonth()+1)+"-"+g(this.getUTCDate())+"T"+g(this.getUTCHours())+":"+g(this.getUTCMinutes())+":"+g(this.getUTCSeconds())+"Z":null;
};
String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(j){return this.valueOf();
};
}var h=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c,i,a={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},b;
function f(j){d.lastIndex=0;
return d.test(j)?'"'+j.replace(d,function(l){var k=a[l];
return typeof k==="string"?k:"\\u"+("0000"+l.charCodeAt(0).toString(16)).slice(-4);
})+'"':'"'+j+'"';
}function e(k,n){var p,q,j,r,m=c,o,l=n[k];
if(l&&typeof l==="object"&&typeof l.toJSON==="function"){l=l.toJSON(k);
}if(typeof b==="function"){l=b.call(n,k,l);
}switch(typeof l){case"string":return f(l);
case"number":return isFinite(l)?String(l):"null";
case"boolean":case"null":return String(l);
case"object":if(!l){return"null";
}c+=i;
o=[];
if(Object.prototype.toString.apply(l)==="[object Array]"){r=l.length;
for(p=0;
p<r;
p+=1){o[p]=e(p,l)||"null";
}j=o.length===0?"[]":c?"[\n"+c+o.join(",\n"+c)+"\n"+m+"]":"["+o.join(",")+"]";
c=m;
return j;
}if(b&&typeof b==="object"){r=b.length;
for(p=0;
p<r;
p+=1){if(typeof b[p]==="string"){q=b[p];
j=e(q,l);
if(j){o.push(f(q)+(c?": ":":")+j);
}}}}else{for(q in l){if(Object.prototype.hasOwnProperty.call(l,q)){j=e(q,l);
if(j){o.push(f(q)+(c?": ":":")+j);
}}}}j=o.length===0?"{}":c?"{\n"+c+o.join(",\n"+c)+"\n"+m+"}":"{"+o.join(",")+"}";
c=m;
return j;
}}if(typeof aU.stringify!=="function"){aU.stringify=function(j,l,k){var m;
c="";
i="";
if(typeof k==="number"){for(m=0;
m<k;
m+=1){i+=" ";
}}else{if(typeof k==="string"){i=k;
}}b=l;
if(l&&typeof l!=="function"&&(typeof l!=="object"||typeof l.length!=="number")){throw new Error("JSON.stringify");
}return e("",{"":j});
};
}}());
var aO=(function(){function a(d,e){if(d==null){return e.push("!n");
}if(typeof d==="number"){return e.push("!"+d);
}if(typeof d==="string"){if(d[d.length-1]=="\\"){return e.push("'"+d.replace(/'/g,"\\'")+"u005C'");
}else{return e.push("'"+d.replace(/'/g,"\\'")+"'");
}}if(typeof d==="boolean"){return e.push(d?"!t":"!f");
}if(d instanceof Array){e.push("*");
for(var f=0;
f<d.length;
f++){a(d[f],e);
}return e.push(")");
}if(typeof d=="object"){e.push("(");
for(var c in d){if(d.hasOwnProperty(c)){e.push(c);
a(d[c],e);
}}return e.push(")");
}return e.push("!n");
}function b(d){var c=[];
a(d,c);
return c.join("");
}return{stringify:b};
})();
var al=aJ.ue,aG=aJ.ue_log_idx?"2":"1",aZ="//"+al.furl+"/1/batch/"+aG+"/OE/",ar="/",af="$",at="&",aW="=",aX=",",ak="_",a2=":",ah="%",a0=2000,aR=60000,aY=100,aF=5,aA=1000,ax,aQ,aE={},aT=function(a){return(""+a).length;
},aj=(am.JSON&&am.JSON.stringify)||(aU&&aU.stringify),aq=aO&&aO.stringify,aC=function(a){return(a&&a.r)||al.rid;
},ai=function(a){return(a&&a.s)||al.sid;
},aN=function(a){return(a&&a.m)||al.mid;
},ag=function(a){return(a&&a.sn)||al.sn;
},az=function(b,e,d,c,f){var a=aT(c);
if(f!==null){a+=aT(f)+aT(d)+2;
}if(!aQ[b]){a+=aT(b)+aT(e)+2;
if(aQ.length>0){a++;
}}else{if(!aQ[b][e]){a+=aT(e)+1;
if(aQ[b].length>0){a++;
}}else{a++;
}}return a;
},aS=function(b,c,d){var a=d&&d.t?d.t:al.d();
aH(b,c,d,a);
},aw=function(){if(ax===0){return;
}var b="",d,c,e,a;
for(e in aQ){if(aQ.hasOwnProperty(e)){if(b!==""){b+=ar;
}b+=e+af;
d=aQ[e];
c=true;
for(a in d){if(d.hasOwnProperty(a)){if(!c){b+=at;
}c=false;
b+=a+aW+d[a];
}}}}al.w=b;
return aZ+b;
},ae=function(){ax=0;
aQ=[];
},au=function(c,a){var b=aw();
if(b){ap(b,c,a);
}ae();
},aL=function(a,j,u,d,f){if(f){u=u||{};
u.r=u.r||f;
}var o=aC(u)+":"+j;
aE[o]=(aE[o]||0)+1;
if(aE[o]>aA){var k="ns '"+j+"' reached the max no of calls ("+aA+") - aborting log of "+a;
if(aE[o]==(aA+1)){aS({m:k,f:"forester-client.js",logLevel:"ERROR"},"jserr",u);
}return;
}var b=aN(u)+a2+ai(u)+a2+aC(u),s=0,r,p=""+d,q=a,c,l,i,x,t="s",m=typeof a,h=u&&u.n||false,v=!u||!u.img?1:0,n,g,e;
if(aJ.ue_fcsn&&ag(u)){b+=a2+ag(u);
}if(m=="undefined"){q="";
t="u";
}else{if(a===null){q="";
t=null;
}else{if(m=="boolean"){q=a?"1":"0";
t="b";
}else{if(m=="number"&&!isNaN(a)&&isFinite(a)){q=""+a;
t="n";
}else{if(m=="object"){if(u&&u.c&&aq){q=aq(a);
t="c";
}else{if(aj){q=aj(a);
t="j";
}else{q=""+a;
}}}}}}}q=am.encodeURIComponent(q);
e=a0-aT(b)-aT(j)-aT(p)-2;
if(t!==null){e-=(aT(t)+2);
}while(q!==""){s++;
n=az(b,j,q,p,t);
g=a0-ax;
if(n<=g){c=q;
l="";
g-=n;
ax+=n;
}else{if(aT(q)<=e){au(v,h);
continue;
}else{i=g-(n-aT(q));
if(aF<=i){i-=q.charAt(i-1)==ah?1:q.charAt(i-2)==ah?2:0;
c=q.substr(0,i);
l=q.substr(i);
g=0;
ax=a0;
if(!r){r=1+Math.ceil(aT(l)/e);
}}else{if(a0-(n-aT(q))<aF){return;
}au(v,h);
continue;
}}}if(!aQ[b]){aQ[b]=[];
}if(aJ.ue_log_idx){al.ue_idx=al.ue_idx||{};
al.ue_idx[j]=al.ue_idx[j]||0;
x=al.ue_idx[j]+a2+(t!==null?t+a2+c+a2+p:p);
al.ue_idx[j]+=1;
}else{x=t!==null?t+a2+c+a2+p:p;
}if(r){x+=a2+s+ak+r;
}if(!aQ[b][j]){aQ[b][j]=x;
}else{aQ[b][j]+=aX+x;
}if(g===0||h){au(v,h);
}q=l;
}},aH=function(c,d,e,a,b){if(aJ.ue_lnb){am.setTimeout(function(){aL(c,d,e,a,b);
},0);
}else{aL(c,d,e,a,b);
}},an=function(){if(!al.lr){return;
}var b=al.lr.length,a,c;
for(c=0;
c<b;
c++){a=al.lr[c];
aH(a[1],a[2],a[3],a[4],a[5]);
}al.lr=null;
},aB=1,aV=[],aM,aI=0,ad,aD=function(){var d;
if(window.XMLHttpRequest){try{if(window.XDomainRequest){d=new XDomainRequest();
d.onerror=function(){};
d.ontimeout=function(){};
d.onprogress=function(){};
d.onload=function(){};
d.timeout=0;
aI=1;
}else{d=new XMLHttpRequest();
aI=aI||("withCredentials" in d?1:0);
}}catch(c){return;
}}else{if(window.ActiveXObject&&window.XDomainRequest){if(ad){d=new ActiveXObject(ad);
}else{var a=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.5.0","MSXML2.XMLHTTP.4.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];
for(var e=0;
e<a.length;
e++){try{d=new ActiveXObject(a[e]);
aI=1;
ad=a[e];
}catch(b){continue;
}break;
}}}}return d;
},ap=function(b,e,f){if(!aJ.ue_lwl||f||aJ.ue.isl){if(e&&aB){aB=0;
try{var a=aD();
if(a&&aI){a.open("GET",b,true);
a.send();
aB=1;
}}catch(c){if(aJ.ue_isrw&&aJ.ue.tag){aJ.ue.tag("flsajaxerr");
}}}if(!e||!aB){var d=new Image();
d.src=b;
}if(!aJ.ue.ielfc){aJ.ue.ielfc=[];
}aJ.ue.ielfc.push(b);
}else{aV.push(b);
}},a1=function(){if(!aJ.ue||!aJ.ue.isl){return;
}if(aV.length===0){am.clearInterval(aM);
}else{var a=aV.shift();
ap(a,1,1);
}},w=function(a){if(!w.executed){au(0,1);
w.executed=1;
}},ac=function(a){au(1,1);
},ao=am.onbeforeunload,av=function(){if(!window.chrome){am.onbeforeunload=function(a){if(ao){ao(a);
}w(a);
};
}else{al.attach("beforeunload",w);
al.ulh.push(w);
}};
av();
if(aJ.ue.attach){aJ.ue.attach("load",ac);
}am.setInterval(function(){au(1,1);
},aR);
aM=am.setInterval(a1,aY);
ae();
an();
aJ.ue.log=aS;
if(am.amznJQ&&am.amznJQ.declareAvailable){am.amznJQ.declareAvailable("forester-client");
}if(am.P&&am.P.register){am.P.register("forester-client",function(){});
}if(aP){aP("ld",ay,{wb:1});
}})(ue_csm,window);
(function(c,d){if(!c.useCel||c.ue_cel){return;
}c.ue_cel=(function(){var p=600000,v=[],u=[],y="csmCELLSframework",w="cel",t,b=c.ue,x=c.uet,z=c.uex;
function r(){var f=d.performance||d.webkitPerformance,g=f&&f.navigation&&f.navigation.type==2,h=document.ue_backdetect&&document.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,e=b.bfini;
if(g||(e&&(e>1))||(!e&&h&&(h>1))){return 1;
}return 0;
}b.isBF=r();
if(b.isBF){b.log({k:"bft",t:b.d()},w,{c:1});
return;
}if(typeof x=="function"){x("bb",y,{wb:1});
}function s(){var h=v.length;
if(h>0){var g=[];
for(var e=0;
e<h;
e++){var f=v[e].api;
if(f.ready()){f.on({ts:b.d,ns:w});
u.push(v[e]);
b.log({k:"mso",n:v[e].name,t:b.d()},w,{c:1});
}else{g.push(v[e]);
}}v=g;
}}setTimeout(s,0);
function q(e){if(!q.executed){for(var f=0;
f<u.length;
f++){if(u[f].api.off){u[f].api.off({ts:b.d,ns:w});
}}b.log({k:"eod",t0:b.t0,t:b.d()},w,{n:1,img:1,b:1,c:1});
q.executed=1;
for(var g=0;
g<u.length;
g++){v.push(u[g]);
}u=[];
clearTimeout(t);
}}if(b.attach){if(d.onpagehide||d.onpagehide===null){b.attach("pagehide",q);
}else{b.attach("beforeunload",q);
}}else{var a=d.onbeforeunload;
d.onbeforeunload=function(e){if(typeof a=="function"){a(e);
}q(e);
};
}t=setTimeout(q,p);
if(typeof z=="function"){z("ld",y,{wb:1});
}return{registerModule:function(f,e){v.push({name:f,api:e});
b.log({k:"mrg",n:f,t:b.d()},w,{c:1});
s();
},reset:function(){b.log({k:"rst",t0:b.t0,t:b.d()},w,{r:b.rid,c:1});
v=v.concat(u);
var f=v.length;
for(var e=0;
e<f;
e++){v[e].api.off();
v[e].api.reset();
}s();
clearTimeout(t);
t=setTimeout(q,p);
q.executed=0;
}};
})();
})(ue_csm,window);
(function(e,f,d){if(!e.useCel||e.ue_pdm){return;
}if(ue.isBF){return;
}e.ue_pdm=(function(){var a,b,r,s,u,v,y="csmCELLSpdm",w,c=e.ue,x=e.uet,z=e.uex;
if(typeof x=="function"){x("bb",y,{wb:1});
}function A(){var g={w:a.width,aw:a.availWidth,h:a.height,ah:a.availHeight,cd:a.colorDepth,pd:a.pixelDepth};
var h={w:d.body.scrollWidth,h:d.body.scrollHeight};
if(!u||u.w!=g.w||u.h!=g.h||u.aw!=g.aw||u.ah!=g.ah||u.pd!=g.pd||u.cd!=g.cd){u=g;
u.t=r();
u.k="sci";
c.log(u,w,{c:1});
}if(!v||v.w!=h.w||v.h!=h.h){v=h;
v.t=r();
v.k="doi";
c.log(v,w,{c:1});
}b=setTimeout(A,s);
}function B(){c.log({k:"ebl",t:r()},w,{c:1});
}function t(){c.log({k:"efo",t:r()},w);
}return{on:function(g){s=g.timespan||500;
r=g.ts;
w=g.ns;
a=f.screen;
if(c.attach){c.attach("blur",B,f);
c.attach("focus",t,f);
}setTimeout(A,0);
if(typeof z=="function"){z("ld",y,{wb:1});
}},off:function(g){clearTimeout(b);
if(c.detach){c.detach("blur",B,f);
c.detach("focus",t,f);
}},ready:function(){return d.body;
},reset:function(){v=null;
u=null;
}};
})();
if(e.ue_cel){e.ue_cel.registerModule("page module",e.ue_pdm);
}})(ue_csm,window,document);
(function(d,c){if(!d.useCel||d.ue_vpm){return;
}if(ue.isBF){return;
}d.ue_vpm=(function(){var o,b,n,m,r="csmCELLSvpm",p,a=d.ue,q=d.uet,s=d.uex;
if(typeof q=="function"){q("bb",r,{wb:1});
}function t(){var e={w:c.innerWidth,h:c.innerHeight,x:c.pageXOffset,y:c.pageYOffset};
if(!o||o.w!=e.w||o.h!=e.h||o.x!=e.x||o.y!=e.y){e.t=m();
e.k="vpi";
o=e;
a.log(o,p,{c:1});
}b=setTimeout(t,n);
}return{on:function(e){m=e.ts;
p=e.ns;
n=e.timespan||100;
setTimeout(t,0);
if(typeof s=="function"){s("ld",r,{wb:1});
}},off:function(e){clearTimeout(b);
},ready:function(){return 1;
},reset:function(){o=undefined;
},getVpi:function(){return o;
}};
})();
if(d.ue_cel){d.ue_cel.registerModule("viewport module",d.ue_vpm);
}})(ue_csm,window);
(function(j,h,i){var f=j.ue||{};
function g(){return j.useCelFF&&!f.isBF&&!j.ue_fem&&i.querySelector&&h.getComputedStyle&&[].forEach;
}if(!g()){return;
}j.ue_fem=(function(){var ad=50,b=10,aD=3000,aa,aq="csmCELLSfem",X,aE=[],Z=function(){},ae=[],ak,au,at,c,aA=!!h.MutationObserver,V,av,d="DOMAttrModified",am="DOMNodeInserted",Y="DOMNodeRemoved",e,ab,ao=-aD;
if(typeof uet=="function"){uet("bb",aq,{wb:1});
}function ay(){window.setTimeout(function(){ae.splice(0).forEach(function(k){f.log(k,X,{c:1});
});
},0);
}function an(l,k){ae.push({n:l.cel_n,t:k,k:"ewd"});
}function a(l,k){ae.push({n:l.cel_n,w:l.cel_b.w,h:l.cel_b.h,d:l.cel_b.d,x:l.cel_b.x,y:l.cel_b.y,t:k,k:"ewi",cl:l.className});
}function ax(l,k){ae.push({n:l.cel_n,w:l.cel_b.w,h:l.cel_b.h,d:l.cel_b.d,x:l.cel_b.x,y:l.cel_b.y,t:k,k:"ewi"});
}function ar(m){var p={x:h.pageXOffset,y:h.pageYOffset};
for(var q=0;
q<aE.length;
q++){var l=aE[q];
if(!l.w||!l.w.length){continue;
}for(var o=0;
o<l.w.length;
o++){var n=l.w[o],k=aB(n,p);
if(k&&!n.cel_b){n.cel_b=k;
a(n,m);
}else{if(k&&ac(n.cel_b,k)){n.cel_b=k;
ax(n,m);
}}}}}function aF(k){if(k.c){return i.getElementsByClassName(k.c);
}if(k.id){return[i.getElementById(k.id)];
}return i.querySelectorAll(k.s);
}function ah(m){for(var k=0;
k<aE.length;
k++){var l=aE[k],r=aF(l),p=(l.w||[]),q;
for(q=0;
q<p.length;
q++){var n=p[q];
if(!ak.contains(n)){an(n,m);
}}l.w=[];
for(q=0;
q<r.length;
q++){var o=r[q];
if(!o){continue;
}if(!o.cel_n){o.cel_n=o.getAttribute("cel_widget_id")||(l.id_gen||Z)(o,q)||o.id;
}l.w.push(o);
}}aG();
}function aB(m,k){try{return aj(m,k);
}catch(l){}}function aj(m,k){if(!m){return;
}var l=m.getBoundingClientRect();
return{x:(l.left+k.x)|0,y:(l.top+k.y)|0,w:l.width|0,h:l.height|0,d:(m.offsetWidth===0&&m.offsetHeight===0)|0};
}function ap(k,l){if(k>l){return k-l<3;
}else{return l-k<3;
}}function ac(k,l){return !(ap(k.x,l.x)&&ap(k.y,l.y)&&ap(k.w,l.w)&&ap(k.h,l.h)&&(k.d===l.d));
}function aC(){if(!ab){ab=h.setTimeout(function(){ab=null;
ai("dwe",ah);
ay();
},ad);
}}function aG(){if(!ab&&!e){e=h.setTimeout(function(){e=null;
ai("dwpc",ar);
ay();
},ad);
}}function aw(k,l){if(k<=b){return 0;
}if((l-ao)>=aD){ao=l;
return 0;
}ue_fem.off();
return 1;
}function ai(k,n){var m=aa();
n(m);
var l=aa(),o=l-m,p=aw(o,l);
if(ae.length||p){ae.push({k:"ewt",e:k,d:o,ex:p,t:aa()});
}}function ag(){var k={attributes:true,subtree:true},l={childList:true};
V=new MutationObserver(aG);
av=new MutationObserver(aC);
V.observe(ak,k);
av.observe(ak,l);
av.observe(au,k);
}function af(){at.call(ak,d,aG);
at.call(ak,am,aC);
at.call(ak,Y,aC);
at.call(au,am,aG);
at.call(au,Y,aG);
}function W(){if(aA){ag();
}else{af();
}}function az(){if(av){av.disconnect();
av=null;
}if(V){V.disconnect();
V=null;
}c.call(ak,d,aG);
c.call(ak,am,aC);
c.call(ak,Y,aC);
c.call(au,am,aG);
c.call(au,Y,aG);
}function al(){return at&&c&&ak&&ak.contains&&ak.getBoundingClientRect&&aa;
}return{on:function(l){ak=i.body;
au=i.head;
at=ak.addEventListener;
c=ak.removeEventListener;
aa=l.ts;
X=l.ns;
aE=j.cel_widgets||[];
function k(){if(al()){W();
aC();
}}if(f.deffered){k();
}else{if(f.attach){f.attach("load",k);
}}if(typeof uex=="function"){uex("ld",aq,{wb:1});
}},off:function(){if(al()){az();
}},ready:function(){return f.log;
},reset:function(){aE=j.cel_widgets||[];
}};
})();
if(j.ue_cel&&j.ue_fem){j.ue_cel.registerModule("features module",j.ue_fem);
}})(ue_csm,window,document);
