var _yt_www={};(function(m){var window=this;var pa,aaa;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.da=function(a){return void 0!==a};m.h=function(a,b,c){a=a.split(".");c=c||m.ea;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m.da(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};m.k=function(a,b){for(var c=a.split("."),d=b||m.ea,f;f=c.shift();)if(null!=d[f])d=d[f];else return null;return d};m.fa=function(){};m.ga=function(a){a.getInstance=function(){return a.$a?a.$a:a.$a=new a}};
m.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ia=function(a){return"array"==m.ha(a)};m.ja=function(a){var b=m.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.ka=function(a){return"string"==typeof a};m.la=function(a){return"number"==typeof a};m.ma=function(a){return"function"==m.ha(a)};m.na=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.oa=function(a){return a[pa]||(a[pa]=++aaa)};
var baa=function(a,b,c){return a.call.apply(a.bind,arguments)};var caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.l=function(a,b,c){m.l=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return m.l.apply(null,arguments)};
m.p=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.r=function(a,b){function c(){}c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,g){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};m.qa=function(a){m.qa[" "](a);return a};
m.ra=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m.ra);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};m.ta=function(a){return(0,window.encodeURIComponent)(String(a))};
m.ua=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};m.va=function(a,b){return-1!=a.indexOf(b)};
m.wa=function(a,b){for(var c=0,d=(0,m.xa)(String(a)).split("."),f=(0,m.xa)(String(b)).split("."),g=Math.max(d.length,f.length),n=0;0==c&&n<g;n++){var q=d[n]||"",t=f[n]||"",z=RegExp("(\\d*)(\\D*)","g"),H=RegExp("(\\d*)(\\D*)","g");do{var T=z.exec(q)||["","",""],ca=H.exec(t)||["","",""];if(0==T[0].length&&0==ca[0].length)break;c=ya(0==T[1].length?0:(0,window.parseInt)(T[1],10),0==ca[1].length?0:(0,window.parseInt)(ca[1],10))||ya(0==T[2].length,0==ca[2].length)||ya(T[2],ca[2])}while(0==c)}return c};
var ya=function(a,b){return a<b?-1:a>b?1:0};m.za=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Aa=function(a){var b=m.ka(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,f){return b+f.toUpperCase()})};m.Ba=function(a,b,c){b=m.Ca(a,b,c);return 0>b?null:m.ka(a)?a.charAt(b):a[b]};
m.Ca=function(a,b,c){for(var d=a.length,f=m.ka(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return g;return-1};m.Da=function(a,b){return 0<=(0,m.Ea)(a,b)};m.Fa=function(a,b){var c=(0,m.Ea)(a,b),d;(d=0<=c)&&m.Ga(a,c);return d};m.Ga=function(a,b){m.Ha.splice.call(a,b,1)};m.Ia=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.Ja=function(a,b,c){return 2>=arguments.length?m.Ha.slice.call(a,b):m.Ha.slice.call(a,b,c)};
m.Ka=function(){this.ob=this.ob;this.ua=this.ua};m.La=function(a,b){m.Ma(a,m.p(m.Na,b))};m.Ma=function(a,b){a.ua||(a.ua=[]);a.ua.push(m.da(void 0)?(0,m.l)(b,void 0):b)};m.Na=function(a){a&&"function"==typeof a.dispose&&a.dispose()};m.Oa=function(){m.Ka.call(this);this.oa=[];this.Cb={}};m.Qa=function(a){Ra(m.Sa,arguments)};m.s=function(a,b){return a in m.Sa?m.Sa[a]:b};m.u=function(a,b){m.ma(a)&&(a=m.Ta(a));return window.setTimeout(a,b)};
m.Ua=function(a,b){m.ma(a)&&(a=m.Ta(a));return window.setInterval(a,b)};m.Va=function(a){window.clearTimeout(a)};m.Wa=function(a){window.clearInterval(a)};m.Ta=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw m.Xa(b),b;}}:a};m.Xa=function(a,b){if(window&&window.yterr){var c=m.k("yt.www.errors.log");c?c(a,b):(c=m.s("ERRORS")||[],c.push([a,b]),m.Qa("ERRORS",c))}};m.Ya=function(a){Ra(m.Za,arguments)};m.$a=function(a){return a in m.Za};
m.ab=function(a,b,c){var d=b||{};if(a=a in m.Za?m.Za[a]:c)for(var f in d)a=a.replace(new RegExp("\\$"+f,"gi"),function(){return d[f]});return a};var Ra=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};m.v=function(a,b,c){var d=bb();if(d){var f=d.subscribe(a,function(){if(!m.cb||m.cb!=f){var d=arguments,n=function(){db[f]&&b.apply(c||window,d)};try{eb[a]?n():m.u(n,0)}catch(q){m.Xa(q)}}},c);db[f]=!0;fb[a]||(fb[a]=[]);fb[a].push(f);return f}return 0};
m.gb=function(a){var b=bb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.w)(a,function(a){b.unsubscribeByKey(a);delete db[a]}))};m.x=function(a,b){var c=bb();return c?c.publish.apply(c,arguments):!1};m.hb=function(a,b){eb[a]=!0;var c=bb(),c=c?c.publish.apply(c,arguments):!1;eb[a]=!1;return c};var bb=function(){return m.k("yt.pubsub.instance_")};m.ib=function(a){if(a.classList)return a.classList;a=a.className;return m.ka(a)&&a.match(/\S+/g)||[]};
m.y=function(a,b){return a.classList?a.classList.contains(b):m.Da(m.ib(a),b)};m.A=function(a,b){a.classList?a.classList.add(b):m.y(a,b)||(a.className+=0<a.className.length?" "+b:b)};m.jb=function(a,b){if(a.classList)(0,m.w)(b,function(b){m.A(a,b)});else{var c={};(0,m.w)(m.ib(a),function(a){c[a]=!0});(0,m.w)(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d}};
m.B=function(a,b){a.classList?a.classList.remove(b):m.y(a,b)&&(a.className=(0,m.kb)(m.ib(a),function(a){return a!=b}).join(" "))};m.lb=function(a,b,c){c?m.A(a,b):m.B(a,b)};m.mb=function(a,b,c){return Math.min(Math.max(a,b),c)};m.nb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.ob=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};m.pb=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};m.qb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
m.rb=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<sb.length;g++)c=sb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var tb=function(a){var b=arguments.length;if(1==b&&m.ia(arguments[0]))return tb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};var ub=function(){var a=m.ea.document;return a?a.documentMode:void 0};m.vb=function(a){return wb[a]||(wb[a]=0<=m.wa(xb,a))};
m.yb=function(a){return m.zb&&m.Ab>=a};m.C=function(a){return m.ka(a)?window.document.getElementById(a):a};m.Bb=function(a){var b=window.document;return m.ka(a)?b.getElementById(a):a};m.D=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=m.Cb("*",a,b)[0];return d||null};
m.Cb=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},f=0,g=0,n;n=c[g];g++)a==n.nodeName&&(d[f++]=n);d.length=f;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(g=f=0;n=c[g];g++)a=n.className,"function"==typeof a.split&&m.Da(a.split(/\s+/),b)&&(d[f++]=n);d.length=f;return d}return c};
m.Db=function(a,b){m.nb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Eb?a.setAttribute(Eb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};m.Fb=function(a,b,c){return m.Gb(window.document,arguments)};
m.Gb=function(a,b){var c=b[0],d=b[1];if(!kaa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',m.ua(d.name),'"');if(d.type){c.push(' type="',m.ua(d.type),'"');var f={};m.rb(f,d);delete f.type;d=f}c.push(">");c=c.join("")}c=a.createElement(c);d&&(m.ka(d)?c.className=d:m.ia(d)?c.className=d.join(" "):m.Db(c,d));2<b.length&&m.Hb(a,c,b,2);return c};
m.Hb=function(a,b,c,d){function f(c){c&&b.appendChild(m.ka(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];!m.ja(g)||m.na(g)&&0<g.nodeType?f(g):(0,m.w)(laa(g)?m.Ia(g):g,f)}};m.Ib=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};m.Jb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};var maa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
var naa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};m.Kb=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var laa=function(a){if(a&&"number"==typeof a.length){if(m.na(a))return"function"==typeof a.item||"string"==typeof a.item;if(m.ma(a))return"function"==typeof a.item}return!1};m.Lb=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var f=0;a&&(c||f<=d);){if(b(a))return a;a=a.parentNode;f++}return null};
m.Mb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};m.Nb=function(){};var Ob=function(a){if(a instanceof m.Nb)return a;if("function"==typeof a.Jb)return a.Jb(!1);if(m.ja(a)){var b=0,c=new m.Nb;c.next=function(){for(;;){if(b>=a.length)throw m.Pb;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};m.Qb=function(a,b,c){if(m.ja(a))try{(0,m.w)(a,b,c)}catch(d){if(d!==m.Pb)throw d;}else{a=Ob(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(f){if(f!==m.Pb)throw f;}}};
m.Rb=function(a){if(m.ja(a))return m.Ia(a);a=Ob(a);var b=[];m.Qb(a,function(a){b.push(a)});return b};m.Sb=function(a,b,c,d,f,g,n){var q="";a&&(q+=a+":");c&&(q+="//",b&&(q+=b+"@"),q+=c,d&&(q+=":"+d));f&&(q+=f);g&&(q+="?"+g);n&&(q+="#"+n);return q};m.Tb=function(a){if(Ub){Ub=!1;var b=m.ea.location;if(b){var c=b.href;if(c&&(c=m.Vb(c))&&c!=b.hostname)throw Ub=!0,Error();}}return a.match(oaa)};m.Wb=function(a){return a?(0,window.decodeURI)(a):a};m.Vb=function(a){return m.Wb(m.Tb(a)[3]||null)};
m.Xb=function(a){a=m.Tb(a);return m.Sb(null,null,null,null,a[5],a[6],a[7])};m.Zb=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};m.$b=function(a,b,c){if(m.ia(b))for(var d=0;d<b.length;d++)m.$b(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",m.ta(b))};var ac=function(a,b){for(var c in b)m.$b(c,b[c],a);return a};m.bc=function(a){a=ac([],a);a[0]="";return a.join("")};
m.cc=function(a,b){return m.Zb(ac([a],b))};m.dc=function(a,b,c){a&&(c?a&&(a=m.Fb("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),m.Kb(a).body.appendChild(a)):paa(a,b))};var paa=function(a,b){var c=new window.Image,d=""+qaa++;ec[d]=c;c.onload=c.onerror=function(){b&&ec[d]&&b();delete ec[d]};c.src=a;c=eval("null")};m.fc=function(a,b,c){gc(c)[a]=b||(0,m.E)();b||hc(a)};var ic=function(a,b){jc(void 0).yt_sts=a;m.fc("_start",b,void 0)};
var kc=function(a,b,c){var d=lc(c).span;c=gc(c);"number"==typeof b?d[a]=b:b in c&&(d[a]=(0,m.E)()-c[b])};
var mc=function(a){var b=gc(a),c=lc(a).span,d=jc(a),f=m.k("yt.timing.reportbuilder_");if(f){if(f=f(b,c,d,a))nc(f),oc(a),pc();return window.NaN}f={v:2,s:"youtube",action:m.s("TIMING_ACTION")};if(qc.now&&qc.timing){var g=qc.timing.navigationStart+qc.now(),g=Math.round((0,m.E)()-g);d.yt_hrd=g}var g=m.s("TIMING_INFO")||{},n;for(n in g)d[n]=g[n];n=d.srt;delete d.srt;var q;n||0===n||(q=qc.timing||{},n=Math.max(0,q.responseStart-q.navigationStart),(0,window.isNaN)(n)&&d.pt&&(n=d.pt));if(n||0===n)d.srt=n;
d.h5jse&&(g=window.location.protocol+m.k("ytplayer.config.assets.js"),(g=qc.getEntriesByName?qc.getEntriesByName(g)[0]:null)?d.h5jse=Math.round(d.h5jse-g.responseEnd):delete d.h5jse);g=!1;b.aft||(b.pbr&&b.pbs>b.pbr?(b.aft=b.pbr,g=!0):b.pbs?(b.aft=b.pbs,g=!0):b.vr?(b.aft=b.vr,g=!0):b.aft=b.ol);b.gv&&g&&(c.vl=Math.round(b.aft-b.gv));g=b._start;if(!rc){q||(q=qc.timing||{});var t;e:if(t=q,t.msFirstPaint)t=Math.max(0,t.msFirstPaint);else{var z=window.chrome;if(z&&(z=z.loadTimes,m.ma(z))){var z=z(),H=1E3*
Math.min(z.requestTime||window.Infinity,z.startLoadTime||window.Infinity),H=window.Infinity===H?0:t.navigationStart-H;t=Math.max(0,Math.round(1E3*z.firstPaintTime+H)||0);break e}t=0}0<t&&t>g&&(b.fpt=t);t=q.redirectEnd-q.redirectStart;0<t&&(c.rtime_=t);t=q.domainLookupEnd-q.domainLookupStart;0<t&&(c.dns_=t);t=q.connectEnd-q.connectStart;0<t&&(c.tcp_=t);t=q.connectEnd-q.secureConnectionStart;q.secureConnectionStart&&0<t&&(c.stcp_=t);t=q.responseStart-q.requestStart;0<t&&(c.req_=t);t=q.responseEnd-q.responseStart;
0<t&&(c.rcv_=t);rc=!0}for(var T in d)"_"!=T.charAt(0)&&(f[T]=d[T]);d={};T=[];for(var ca in b)"_"!=ca.charAt(0)&&(t=Math.max(Math.round(b[ca]-g),0),d[ca]=t,T.push(ca+"."+t));f.rt=T.join(",");b={};ca=[];for(var sa in c)"_"!=sa.charAt(0)&&(b[sa]=c[sa],ca.push(sa+"."+c[sa]));f.it=ca.join(",");(c=m.k("ytdebug.logTiming"))&&c(f,d,b);oc(a);pc();m.s("EXP_DEFER_CSI_PING")?(sc(),tc=f,uc=m.u(sc,0)):nc(f);return d.aft+(n||0)};
var vc=function(a,b){var c=m.s("TIMING_ACTION"),d=gc(b);if(c&&d._start)if(c=m.s("TIMING_WAIT",[]),!a&&c.length){for(var f=!0,g=0,n=c.length;g<n;++g)if(!(c[g]in d)){f=!1;break}if(f)return mc(b)}else if(d.ol||d.aft)return mc(b);return window.NaN};var wc=function(a){if(m.s("TIMING_WAIT"))a=vc(!1,a);else e:{var b=m.s("TIMING_ACTION"),c=!!m.s("TIMING_WFF"),d=gc(a);if(b&&d._start){if(c&&d.vr||!c&&(d.ol||d.aft)){a=mc(a);break e}a&&mc(a)}a=window.NaN}return a};
var nc=function(a){m.s("EXP_DEFER_CSI_PING")&&(m.Va(uc),tc=null);var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];m.dc(b+"?"+c.substring(1))};var sc=function(a){tc&&(a&&(tc.yt_fss=a),nc(tc))};var gc=function(a){return lc(a).tick};var jc=function(a){return lc(a).info};var lc=function(a){return m.k("ytcsi."+(a||"")+"data_")||oc(a)};
var oc=function(a){var b={tick:{},span:{},info:{}};m.h("ytcsi."+(a||"")+"data_",b,void 0);return b};m.xc=function(){return!!m.k("yt.scheduler.instance")};m.yc=function(){return m.xc()&&m.y(window.document.body,"exp-js-scheduler-more")};m.zc=function(a,b){void 0===b&&(b=window.NaN);var c=m.k("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):m.u(a,b||0)};m.Ac=function(a,b){return m.zc(a,b)};
m.Bc=function(a){var b=m.k("yt.scheduler.instance.cancelJob");b?b(a):m.Va(a)};m.Cc=function(a){for(var b=0,c=a.length;b<c;b++)m.Bc(a[b])};m.Dc=function(a,b,c,d,f){this.name=a;this.deps=b||[];this.page=c||"";this.F=d?m.Ta(d):null;this.C=f?m.Ta(f):null;this.oa=[];this.A=this.B=0};m.Ec=function(a){m.yc()?(m.Bc(a.B),a.B=m.Ac((0,m.l)(a.init,a))):a.init()};
m.Fc=function(a){a.name in Gc&&Hc(a.name);Gc[a.name]={reqs:[],disable:(0,m.l)(a.disable,a)};(0,m.w)(a.deps,function(b){if(!(b in Gc))throw Error("Module "+b+" required by "+a.name);Gc[b].reqs.push(a.name)});a.enable()};var Hc=function(a){if(a in Gc){var b=Gc[a];(0,m.w)(b.reqs,function(a){Hc(a)});try{b.disable()}catch(c){}delete Gc[a]}};m.Ic=function(a){return a&&"readyState"in a?a.readyState:0};
var raa=function(){if(m.s("SCHEDULE_AJAX")&&window.XMLHttpRequest&&!Jc){Kc=m.s("SCHEDULER_BUFFER_LENGTH");var a=window.XMLHttpRequest;Lc=a.prototype.abort;Mc=a.prototype.open;Jc=a.prototype.send;a.prototype.abort=saa;a.prototype.open=taa;a.prototype.send=uaa}};var saa=function(){Nc(!0);Lc.call(this)};var taa=function(){this.url=arguments[1];Mc.apply(this,arguments)};
var uaa=function(){var a=this,b=arguments;if(a.url&&a.url.match(vaa))Jc.apply(a,b);else{if("onloadend"in a)a.addEventListener("loadend",function(){4==m.Ic(a)&&Nc(!0)},!1);else{var c=a.onreadystatechange;a.onreadystatechange=function(){4==m.Ic(a)&&Nc(!0);c&&c.apply(this,arguments)}}Oc.push(function(){Jc.apply(a,b)});Nc()}};var Nc=function(a){a&&(Pc=!1,m.Va(Qc));if(!Pc&&Oc.length)if(Kc&&!waa())m.Va(Rc),Rc=m.u(Nc,100);else{Pc=!0;a=Oc.shift();try{a()}catch(b){Nc(!0)}Qc=m.u(m.p(Nc,!0),5E3)}};
var waa=function(){var a=Kc,b=m.k("yt.player.getPlayerByElement");if(!b)return!0;var b=b("player-api"),c=m.s("ADS_DATA");return b&&(!c||!c.show_instream)&&b.getVideoLoadedFraction&&b.getDuration&&b.getCurrentTime&&b.getPlayerState?(c=b.getVideoLoadedFraction()*b.getDuration()-b.getCurrentTime(),0>=b.getPlayerState()||c>a||.3<b.getVideoLoadedFraction()):!0};m.F=function(a,b){return a?a.dataset?a.dataset[m.Sc(b)]:a.getAttribute("data-"+b):null};
m.Tc=function(a,b){return a?a.dataset?m.Sc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};m.Sc=function(a){return Uc[a]||(Uc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.Vc=function(a,b){var c=m.Wc(a);window.spf.script.load(a,c,b)};m.Xc=function(a,b){var c=m.Wc(a);window.spf.script.ignore(c,b)};m.Yc=function(a){a&&(m.ka(a)?m.Vc(a):m.ia(a)?(0,m.w)(a,function(a){m.Yc(a)}):m.nb(a,function(a,c){m.Vc(c,function(){m.Yc(a)})}))};
m.Wc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),f=c+6;-1<c&&-1<d&&d>f&&(b=a.substring(f,d),b=b.replace(xaa,""),b=b.replace(yaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};var zaa=function(a){a=(0,m.Zc)(a);a=null===a?null:a.split(".").reverse();return(null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
m.$c=function(a,b){m.dc("/gen_204?"+a,b)};var ad=function(a){a=a||{};this.url=a.url||"";this.urlV8=a.url_v8||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||m.qb(Aaa);this.assets=a.assets||{};this.attrs=a.attrs||m.qb(Baa);this.params=a.params||m.qb(Caa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
m.bd=function(a){a instanceof ad||(a=new ad(a));return a};m.cd=function(a){this.j=a};m.dd=function(a){a=(a.j.cookie||"").split(m.ed);for(var b=[],c=[],d,f,g=0;f=a[g];g++)d=f.indexOf("="),-1==d?(b.push(""),c.push(f)):(b.push(f.substring(0,d)),c.push(f.substring(d+1)));return{keys:b,values:c}};m.fd=function(a,b,c){m.gd.set(""+a,b,c,"/","youtube.com")};m.hd=function(a,b){return m.gd.get(""+a,b)};
m.id=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.w)(a.childNodes,function(a){b.appendChild(m.id(a))}):b.innerHTML=a.innerHTML;return b};
m.jd=function(a){if(a=a||window.event){for(var b in a)b in Daa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.wa=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:
a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.Cj=a.pageX;this.Dj=a.pageY}};m.kd=function(a,b,c,d){return m.pb(m.ld,function(f){return f[0]==a&&f[1]==b&&f[2]==c&&f[4]==!!d})};
m.G=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var f=m.kd(a,b,c,d);if(f)return f;var f=++md.count+"",g=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),n;n=g?function(d){d=new m.jd(d);if(!m.Lb(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.jd(b);b.currentTarget=a;return c.call(a,b)};n=m.Ta(n);m.ld[f]=[a,b,c,n,d];a.addEventListener?"mouseenter"==b&&g?a.addEventListener("mouseover",
n,d):"mouseleave"==b&&g?a.addEventListener("mouseout",n,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",n,d):a.addEventListener(b,n,d):a.attachEvent("on"+b,n);return f};m.I=function(a){a&&("string"==typeof a&&(a=[a]),(0,m.w)(a,function(a){if(a in m.ld){var c=m.ld[a],d=c[0],f=c[1],g=c[3],c=c[4];d.removeEventListener?d.removeEventListener(f,g,c):d.detachEvent&&d.detachEvent("on"+f,g);delete m.ld[a]}}))};
m.nd=function(a,b){a=!!a;m.h("_lactCookie",a,window);if(null==m.k("_lact",window)){if(a&&b){var c=m.hd("ACTIVITY","-1");m.h("_lact",(0,window.parseInt)(c,10),window)}else m.h("_lact",-1,window),od();m.G(window.document,"keypress",od);m.G(window.document,"mousedown",od);m.G(window.document,"mouseup",od)}};var od=function(){var a=m.k("_lact",window);null==a&&(m.nd(),a=m.k("_lact",window));var b=(0,m.E)();m.h("_lact",b,window);m.k("_lactCookie",window)&&1E3<=b-a&&m.fd("ACTIVITY",""+b)};
m.pd=function(){var a=m.k("_lact",window);return null==a?-1:Math.max((0,m.E)()-a,0)};m.qd=function(a,b,c){var d=m.Vb(a);if(d==m.Vb(window.location.href)||!d&&0==a.lastIndexOf("/",0))if(a=m.Xb(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&rd(a,b,c)):rd(a,b)};var rd=function(a,b,c){for(var d=0,f=0;f<a.length;++f)d=31*d+a.charCodeAt(f),d%=4294967296;a="s_tempdata-"+d;c=c||5;b=b?m.bc(b):"";m.fd(a,b,c)};
m.sd=function(a,b,c){c=c||"";window.location=m.cc(a,b||{})+c};m.td=function(a){(window.ytspf||{}).enabled?window.spf.navigate(a):m.sd(a)};m.ud=function(a,b,c){var d=m.s("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&m.qd(a,b);if(c)return!1;m.td(a);return!0};var vd=function(a){m.ea.setTimeout(function(){throw a;},0)};
var Eaa=function(){var a=m.ea.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,m.l)(function(a){if(("*"==d||a.origin==
d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!m.va(m.wd,"Trident")&&!m.va(m.wd,"MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m.da(c.next)){c=c.next;var a=c.to;c.to=null;a()}};return function(a){d.next={to:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")?function(a){var b=
window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){m.ea.setTimeout(a,0)}};var xd=function(a,b){yd||Faa();zd||(yd(),zd=!0);Ad.push(new Gaa(a,b))};
var Faa=function(){if(m.ea.Promise&&m.ea.Promise.resolve){var a=m.ea.Promise.resolve();yd=function(){a.then(Bd)}}else yd=function(){var a=Bd;!m.ma(m.ea.setImmediate)||m.ea.Window&&m.ea.Window.prototype.setImmediate==m.ea.setImmediate?(Cd||(Cd=Eaa()),Cd(a)):m.ea.setImmediate(a)}};var Bd=function(){for(;Ad.length;){var a=Ad;Ad=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.Sd.call(c.scope)}catch(d){vd(d)}}}zd=!1};var Gaa=function(a,b){this.Sd=a;this.scope=b};
m.Dd=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};m.Ed=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};m.Fd=function(a,b){this.A=0;this.G=void 0;this.j=this.B=null;this.C=this.F=!1;try{var c=this;a.call(b,function(a){Gd(c,2,a)},function(a){Gd(c,3,a)})}catch(d){Gd(this,3,d)}};m.Hd=function(a){return new m.Fd(function(b){b(a)})};
var Id=function(a,b){if(0==a.A)if(a.B){var c=a.B;if(c.j){for(var d=0,f=-1,g=0,n;n=c.j[g];g++)if(n=n.sg)if(d++,n==a&&(f=g),0<=f&&1<d)break;0<=f&&(0==c.A&&1==d?Id(c,b):(d=c.j.splice(f,1)[0],Jd(c,d,3,b)))}}else Gd(a,3,b)};var Haa=function(a,b){a.j&&a.j.length||2!=a.A&&3!=a.A||Kd(a);a.j||(a.j=[]);a.j.push(b)};
m.Ld=function(a,b,c,d){var f={sg:null,nm:null,om:null};f.sg=new m.Fd(function(a,n){f.nm=b?function(c){try{var f=b.call(d,c);a(f)}catch(z){n(z)}}:a;f.om=c?function(b){try{var f=c.call(d,b);!m.da(f)&&b instanceof Md?n(b):a(f)}catch(z){n(z)}}:n});f.sg.B=a;Haa(a,f);return f.sg};
var Gd=function(a,b,c){if(0==a.A){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(m.Ed(c)){a.A=1;c.then(a.H,a.K,a);return}if(m.na(c))try{var d=c.then;if(m.ma(d)){Iaa(a,c,d);return}}catch(f){b=3,c=f}}a.G=c;a.A=b;Kd(a);3!=b||c instanceof Md||Jaa(a,c)}};var Iaa=function(a,b,c){function d(b){g||(g=!0,a.K(b))}function f(b){g||(g=!0,a.H(b))}a.A=1;var g=!1;try{c.call(b,f,d)}catch(n){d(n)}};var Kd=function(a){a.F||(a.F=!0,xd(a.J,a))};
var Jd=function(a,b,c,d){if(2==c)b.nm(d);else{for(;a&&a.C;a=a.B)a.C=!1;b.om(d)}};var Jaa=function(a,b){a.C=!0;xd(function(){a.C&&Kaa.call(null,b)})};var Md=function(a){m.ra.call(this,a)};var Nd=function(a){this.B=a;this.A=null;var b=this;a.then(function(a){b.A=a})};
var Od=function(a,b){var c=b||{},d=Laa().then(function(b){return b(a,{apiKey:c.Ke||c.apiKey,environment:c.Le||c.environment,helpCenterPath:c.Tz||c.helpCenterPath,locale:c.locale||c.locale,productData:c.Uz||c.productData,receiverUri:c.Vz||c.receiverUri,theme:c.theme||c.theme,window:c.window||c.window})});return new Nd(d)};
var Laa=function(){if(Pd)return Pd;var a=m.k("help.service.Lazy.create");return a?Pd=m.Hd(a):Pd=(new m.Fd(function(a,c){var d=window.document.createElement("script");d.async=!0;d.src="https://www.gstatic.com/inproduct_help/service/lazy.min.js";d.onload=d.onreadystatechange=function(){d.readyState&&"loaded"!=d.readyState&&"complete"!=d.readyState||a(null)};d.onerror=c;(window.document.head||window.document.getElementsByTagName("head")[0]).appendChild(d)})).then(function(){var a=m.k("help.service.Lazy.create");
if(!a)throw Error("Failed to load help.service.Lazy.create from https://www.gstatic.com/inproduct_help/service/lazy.min.js");return a})};var Qd=function(a,b,c){a.B.then(function(a){a[b].apply(a,c)})};var Rd=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var Sd=function(a){return(a=a.exec(m.wd))?a[1]:""};
var Td=function(){this.B=this.A=this.j=0;this.C="";var a=m.k("window.navigator.plugins"),b=m.k("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",f=0,g=c.length;f<g;f++)if(d)if(a)break;else a=c[f];else d=c[f];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;f=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))f=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,f]}else a=[0,0,0];this.C=b;b=a;this.j=b[0];this.A=b[1];this.B=b[2];if(0>=this.j){var n,q,t,z;if(m.Ud)try{n=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(H){n=null}else t=window.document.body,z=window.document.createElement("object"),z.setAttribute("type","application/x-shockwave-flash"),n=t.appendChild(z);if(n&&"GetVariable"in n)try{q=n.GetVariable("$version")}catch(T){q=""}t&&z&&t.removeChild(z);(n=q||"")?(n=n.split(" ")[1].split(","),
n=[(0,window.parseInt)(n[0],10)||0,(0,window.parseInt)(n[1],10)||0,(0,window.parseInt)(n[2],10)||0]):n=[0,0,0];this.j=n[0];this.A=n[1];this.B=n[2]}};var Vd=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.j>b[0]||a.j==b[0]&&a.A>b[1]||a.j==b[0]&&a.A==b[1]&&a.B>=b[2]};
var Wd=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.j&&1==a.A||9==a.j&&0==a.A&&1==a.B?!1:9<=a.j};var Maa=function(a){return m.Xd?!Vd(a,11,2):m.Yd?!Vd(a,11,3):!Wd(a)};m.Zd=function(){return m.$d?"Webkit":m.ae?"Moz":m.zb?"ms":m.be?"O":null};m.ce=function(){return m.$d?"-webkit":m.ae?"-moz":m.zb?"-ms":m.be?"-o":null};m.de=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
m.ee=function(a,b){return a&&b?b instanceof m.de?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};m.fe=function(a,b){var c=m.za(b);if(void 0===a.style[c]){var d=m.Zd()+m.Aa(c);if(void 0!==a.style[d])return d}return c};m.ge=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.he=function(a,b){a.style.display=b?"":"none"};m.ie=function(){this.j="";this.A=je};
var ke=function(a){return a instanceof m.ie&&a.constructor===m.ie&&a.A===je?a.j:"type_error:Const"};var le=function(){this.j="";this.A=me};var ne=function(a){var b=new le;b.j=a;return b};var oe=function(){this.j=pe};var qe=function(){this.j="";this.B=re;this.A=null};m.se=function(a){return a instanceof qe&&a.constructor===qe&&a.B===re?a.j:"type_error:SafeHtml"};
m.te=function(a,b){if(!ue.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toLowerCase()in Naa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");var c=null,d="<"+a;if(b)for(var f in b){if(!ue.test(f))throw Error('Invalid attribute name "'+f+'".');var g=b[f];if(null!=g){if(g instanceof m.ie)g=ke(g);else if("style"==f.toLowerCase()){if(!m.na(g))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof g+" given: "+g);if(!(g instanceof le)){var n=
"",q=void 0;for(q in g){if(!/^[-_a-zA-Z0-9]+$/.test(q))throw Error("Name allows only [-_a-zA-Z0-9], got: "+q);var t=g[q];null!=t&&(t instanceof m.ie?t=ke(t):Oaa.test(t)||(t="zClosurez"),n+=q+":"+t+";")}g=n?ne(n):Paa}g=g instanceof le&&g.constructor===le&&g.A===me?g.j:"type_error:SafeStyle"}else{if(/^on/i.test(f))throw Error('Attribute "'+f+'" requires goog.string.Const value, "'+g+'" given.');if(g instanceof oe)g=g instanceof oe&&g.constructor===oe&&g.j===pe?"":"type_error:SafeUrl";else if(f.toLowerCase()in
Qaa)throw Error('Attribute "'+f+'" requires goog.string.Const or goog.html.SafeUrl value, "'+g+'" given.');}d+=" "+f+'="'+m.ua(String(g))+'"'}}f=void 0;m.da(f)?m.ia(f)||(f=[f]):f=[];!0===Raa[a.toLowerCase()]?d+=">":(c=Saa(f),d+=">"+m.se(c)+"</"+a+">",c=c.Hg());(f=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(f)?c=0:c=null);return ve(d,c)};
var Saa=function(a){function b(a){if(m.ia(a))(0,m.w)(a,b);else{if(!(a instanceof qe)){var g=null;a.On&&(g=a.Hg());a=ve(m.ua(a.yh?a.xh():String(a)),g)}d+=m.se(a);a=a.Hg();0==c?c=a:0!=a&&c!=a&&(c=null)}}var c=0,d="";(0,m.w)(arguments,b);return ve(d,c)};var ve=function(a,b){var c=new qe;c.j=a;c.A=b;return c};m.we=function(a,b){(a=m.C(a))&&a.style&&(m.he(a,b),m.lb(a,"hid",!b))};m.J=function(a){(0,m.w)(arguments,function(a){m.we(a,!0)})};
var xe=function(a){var b=m.s("FEEDBACK_LOCALE_LANGUAGE"),c=m.ye,d=m.s("FEEDBACK_LOCALE_EXTRAS",{});a?m.rb(c,a):m.rb(c,d);try{var f,g=m.k("yt.player.getPlayerByElement");(f=g?g("player-api"):null)&&f.pauseVideo&&f.pauseVideo();var n=Td.getInstance();c.flashVersion=n.getVersion().join(".");f&&(c.playback_id=f.getVideoData().cpn)}catch(q){}return{helpCenterPath:"/youtube",locale:b,productData:c}};
var ze=function(){var a=m.s("SESSION_INDEX"),b=m.s("FEEDBACK_BUCKET_ID"),c={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005"};a&&(c.authuser=a+"");b&&(c.bucket=b);return c};m.Ae=function(a,b){try{var c=(a||"59")+"",d=xe(b),f=ze();Od(c,d).C(f);return!1}catch(g){return!0}};
m.Be=function(a,b,c,d,f,g,n,q){b=(b||"59")+"";d=xe(d);a={context:c,anchor:a,enableSendFeedback:g?!1:!0,trackingParam:n,defaultHelpArticleId:q};m.rb(a,ze());try{var t=Od(b,d);if(f&&!Ce)try{t.j(a),Ce=!0}catch(z){}t.F(a);return!1}catch(H){return!0}};m.De=function(a,b,c,d){return m.Be(void 0,d,b,c,void 0,void 0,void 0,a)};m.Ee=function(){var a=m.hd("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.Fe[d]=c.toString())}};
var Ge=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};var He=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.Ie=function(a){a=void 0!==m.Fe[a]?m.Fe[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.Je=function(a,b){return!!((m.Ie("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var Ke=function(a,b,c){if(b){a=m.ka(a)?m.Bb(a):a;c=m.bd(c);var d=m.qb(c.attrs);d.tabindex=0;var f=m.qb(c.params);f.flashvars=m.bc(c.args);if(m.Ud){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";f.movie=b;b=window.document.createElement("object");for(var g in d)b.setAttribute(g,d[g]);for(g in f)d=window.document.createElement("param"),d.setAttribute("name",g),d.setAttribute("value",f[g]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(g in d)b.setAttribute(g,d[g]);for(g in f)b.setAttribute(g,f[g])}f=window.document.createElement("div");f.appendChild(b);a.innerHTML=f.innerHTML}};m.Me=function(a,b){a=m.ka(a)?m.Bb(a):a;b=m.bd(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=Ne();Vd(c,b.minVersion)?(c=Oe(b,c),Ke(a,c,b)):Pe(a,b,c)};
var Qe=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=m.bd(a);var d=!!b,f=m.C(a.attrs.id),g=f?f.parentNode:null;if(f&&g){if(window!=window.top){var n=null;if(window.document.referrer){var q=window.document.referrer.substring(0,128);zaa(q)||(n=q)}else n="unknown";n&&(d=!0,a.args.framer=n)}n=Ne();if(Vd(n,a.minVersion)){var q=Oe(a,n),t="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(t=f.getAttribute("src")||f.movie);(t!=q||d)&&Ke(g,q,a);Maa(n)&&Taa()}else Pe(g,a,n);c&&c()}else m.u(function(){Qe(a,
b,c)},50)}};var Pe=function(a,b,c){0==c.j&&b.fallback?b.fallback():0==c.j&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+m.ab("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var Oe=function(a,b){var c;(c=Wd(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Vd(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.urlV8||a.url};
var Ne=function(){var a=Td.getInstance(),b=m.Ee.getInstance();b.set("fv",a.getVersion().join("."));b.save();return a};var Taa=function(){var a=m.C("flash10-promo-div"),b=m.Je(m.Ee.getInstance(),107);a&&!b&&m.J(a)};m.Re=function(a,b){var c=a.match(Uaa);window.spf.style.load(a,c?c[1]:"",b)};
var Vaa=function(){if(2.2==Se)return!0;var a;a=m.k("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),m.h("yt.player.utils.videoElement_",a,void 0));try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};var Waa=function(){};m.Te=function(){};m.Ue=function(a){this.j=a};m.Ve=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.j=a};
var We=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.j=a};m.Xe=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.Ye=function(a){return m.Ze(new m.$e(void 0),a)};
m.$e=function(a){this.j=a};m.Ze=function(a,b){var c=[];af(a,b,c);return c.join("")};
var af=function(a,b,c){switch(typeof b){case "string":bf(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(m.ia(b)){var d=b.length;c.push("[");for(var f="",g=0;g<d;g++)c.push(f),f=b[g],af(a,a.j?a.j.call(b,String(g),f):f,c),f=",";c.push("]");break}c.push("{");d="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(f=b[g],"function"!=typeof f&&
(c.push(d),bf(g,c),c.push(":"),af(a,a.j?a.j.call(b,g,f):f,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var bf=function(a,b){b.push('"',a.replace(Xaa,function(a){if(a in cf)return cf[a];var b=a.charCodeAt(0),f="\\u";16>b?f+="000":256>b?f+="00":4096>b&&(f+="0");return cf[a]=f+b.toString(16)}),'"')};m.df=function(a){this.j=a};var ef=function(a){this.j=a};var ff=function(a){this.data=a};var gf=function(a){return!m.da(a)||a instanceof ff?a:new ff(a)};
var hf=function(a){this.j=a};m.jf=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.E)()||!!b&&b>(0,m.E)()};m.kf=function(a){this.j=a};m.lf=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.E)()+1E3*d:0;if((d=d?m.mf:m.nf)&&window.JSON){m.ka(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(f){d.remove(a)}}};m.of=function(a){if(!m.nf&&!m.mf||!window.JSON)return null;var b;try{b=m.nf.get(a)}catch(c){}if(!m.ka(b))try{b=m.mf.get(a)}catch(d){}if(!m.ka(b))return null;try{b=JSON.parse(b,void 0)}catch(f){}return b};
var pf=function(){var a={volume:100,muted:!1},b=m.of("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:m.mb(b.volume,0,100);a.muted=void 0==b.muted?!1:b.muted;return a};
var qf=function(a,b){m.Ka.call(this);this.A=this.$c=a;this.R=b;this.G=!1;this.j={};this.W=this.J=null;this.P=new m.Oa;m.La(this,this.P);this.C={};this.F=this.$=this.B=this.pa=this.ca=null;this.T=!1;this.la=this.H=null;this.fa={};this.Ua=["onReady"];this.Ea=null;this.Ma=0;if(this.K=!!m.s("PLAYER_ENABLE_SHARED_UI"))this.$c=window.document.createElement("div"),this.A.appendChild(this.$c),this.A.style.position="relative";this.za=!1;this.Ia=!!m.s("PLAYER_PERSISTENCE_REFACTOR");rf(this);this.Vd("onVolumeChange",
(0,m.l)(this.Do,this));this.Vd("onError",(0,m.l)(this.Co,this));this.Vd("onTabOrderChange",(0,m.l)(this.Bo,this));this.Vd("WATCH_LATER_VIDEO_ADDED",(0,m.l)(this.Eo,this));this.Vd("WATCH_LATER_VIDEO_REMOVED",(0,m.l)(this.Fo,this))};
var sf=function(a,b){a.pa=b;a.ca=b.clone();a.B=a.ca.attrs.id||a.B;"video-player"==a.B&&(a.B=a.R,a.ca.attrs.id=a.R);a.A.id==a.B&&(a.B=a.B+"-player",a.ca.attrs.id=a.B);var c=a.ca.args,d;if(!(d=a.ca.args.eurl)){d=window.document.location.toString();var f=!!d&&-1!=d.search(Yaa),g=-1!=d.indexOf("/embed/");f!=g&&m.Xa(Error(d+" behavior is not consistent"));d=g?window.document.referrer&&window.document.referrer.substring(0,128)||"unknown":d}c.eurl=d;a.ca.args.enablejsapi="1";a.ca.args.playerapiid=a.R;a.$||
(a.$=tf(a,a.ca.args.jsapicallback||"onYouTubePlayerReady"));a.ca.args.jsapicallback=null;a.K&&(a.ca.args.controls="0");if(c=a.ca.attrs.width)a.A.style.width=m.ge(Number(c)||c,!0);if(c=a.ca.attrs.height)a.A.style.height=m.ge(Number(c)||c,!0);a.A.style.overflow="hidden"};var uf=function(a){a.ca.loaded||(a.ca.loaded=!0,"0"!=a.ca.args.autoplay?a.j.loadVideoByPlayerVars(a.ca.args):a.j.cueVideoByPlayerVars(a.ca.args))};
var vf=function(a){if(!m.da(a.ca.disable.flash)){var b=a.ca.disable,c;c=Vd(Ne(),a.ca.minVersion);b.flash=!c}return!a.ca.disable.flash};var wf=function(a){var b=xf(a);b&&b.stopVideo&&b.stopVideo();if(vf(a)){var c=a.ca;b&&b.getUpdatedConfigurationData&&(b=m.bd(b.getUpdatedConfigurationData()),b.args.video_id==c.args.video_id&&(c=b));c.args.autoplay=1;c.args.html5_unavailable="1";sf(a,c);yf(a,"flash")}};
var yf=function(a,b){if(!a.ga()){if(!b){var c;if(!(c=!a.ca.html5&&vf(a))){if(!m.da(a.ca.disable.html5)){if(c=Vaa())c=zf(a)||a.ca.assets.js;a.ca.disable.html5=!c;c||(a.ca.args.html5_unavailable="1")}c=!!a.ca.disable.html5}b=c?vf(a)?"flash":"unsupported":"html5"}("flash"==b?a.dw:"html5"==b?a.ew:a.gw).call(a);a.K&&!a.za&&Zaa(a)}};var zf=function(a){var b=!0;a.Ia&&((b=xf(a))&&a.ca?(a=a.ca,a=m.F(b,"version")==a.assets.js):a=!1,b=a);return b&&!!m.k("yt.player.Application.create")};
var xf=function(a){var b=m.C(a.B);!b&&a.A&&a.A.querySelector&&(b=a.A.querySelector("#"+a.B));return b};var Af=function(a,b,c){var d=b[c];return function(){try{return a.Ea=null,d.apply(b,arguments)}catch(f){"Bad NPObject as private data!"!=f.message&&(f.message+=" ("+c+")",a.Ea=f,m.Xa(f,"WARNING"))}}};
var rf=function(a){a.G=!1;if(a.W)for(var b in a.C)a.W(b,a.C[b]);a.J=null;a.W=null;for(var c in a.j)a.j[c]=null;a.j.addEventListener=(0,m.l)(a.Vd,a);a.j.removeEventListener=(0,m.l)(a.Pr,a);a.j.destroy=(0,m.l)(a.dispose,a);a.j.getLastError=(0,m.l)(a.Nr,a);a.j.getPlayerType=(0,m.l)(a.Or,a);a.j.getCurrentVideoConfig=(0,m.l)(a.Mr,a);a.j.loadNewVideoConfig=(0,m.l)(a.vi,a);a.j.isReady=(0,m.l)(a.Qr,a)};
var tf=function(a,b){var c=b;if("string"==typeof b){if(a.fa[b])return a.fa[b];c=function(){var a=m.k(b);a&&a.apply(m.ea,arguments)};a.fa[b]=c}return c?c:null};var $aa=function(a,b){var c="ytPlayer"+b+a.R;a.C[b]=c;m.ea[c]=function(c){m.u(function(){a.ga()||a.P.publish(b,c)},0)};return c};var Bf=function(a){return(a=xf(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var Cf=function(a){m.fc("dcp");a.cancel();rf(a);a.F=null;a.ca&&(a.ca.loaded=!1);var b=xf(a);"html5"==Bf(a)?a.la=b:b&&b.destroy&&b.destroy();a.K&&m.Jb(xf(a));m.Ib(a.$c)};var Zaa=function(a){a.ca.assets.js_sharedui&&(a.za=!0,m.Re(a.ca.assets.css_sharedui),m.Vc(a.ca.assets.js_sharedui,(0,m.l)(function(){this.j.addEventListener("onReady",(0,m.l)(this.Kt,this))},a)))};
m.Df=function(a,b){a=m.ka(a)?m.Bb(a):a;b=m.bd(b);var c=Ef+"_"+m.oa(a),d=Ff[c];if(d)return d.vi(b),d.j;d=new qf(a,c);Ff[c]=d;m.x("player-added",d.j);m.Ma(d,m.p(aba,d));m.u(function(){d.vi(b)},0);return d.j};var Gf=function(){for(var a in Ff){var b=Ff[a];b&&b.cancel()}};m.Hf=function(a){if(a=m.C(a))a=Ef+"_"+m.oa(a),(a=Ff[a])&&a.dispose()};var aba=function(a){Ff[a.getId()]=null};m.If=function(a){a=m.C(a);if(!a)return null;var b=Ef+"_"+m.oa(a),c=Ff[b];c||(c=new qf(a,b),Ff[b]=c);return c.j};
var bba=function(){m.h("yt.player.exports.navigate",m.ud,void 0);m.h("yt.player.embed",m.Df,void 0);m.h("yt.player.destroy",m.Hf,void 0);m.h("yt.player.cancelAll",Gf,void 0);m.h("yt.player.getPlayerByElement",m.If,void 0);m.h("yt.player.exports.feedbackStart",m.Ae,void 0);m.h("yt.player.exports.feedbackShowArticle",m.De,void 0);m.h("yt.util.activity.init",m.nd,void 0);m.h("yt.util.activity.getTimeSinceActive",m.pd,void 0);m.h("yt.util.activity.setTimestamp",od,void 0);Jf=Jf||!!m.s("PLAYER_WATCH_WHILE")||
!!m.hd("watch_while");var a=m.k("ytplayer.config");Kf(a);m.k("ytspf.enabled")&&(Lf=m.Ua(Mf,5E3),(a=m.Nf())?(a.addEventListener("onReady",Mf),a.addEventListener("onStateChange",Mf),Jf&&(a.addEventListener("onReady",Of),a.addEventListener("onStateChange",Of))):Pf("unable to init PP monitor"))};
var Kf=function(a){Gf();if(a=a||null){var b=m.Nf(),c=!0;b&&b.getVideoData&&(c=b.getVideoData(),c=c.video_id!=a.args.video_id||c.list!=a.args.list);c?(Qf="",m.Df("player-api",a)):b.playVideo();a=m.bd(a);a.loaded=!0}Of();Mf();m.h("ytplayer.config",a,void 0)};m.Nf=function(){var a=m.k("yt.player.getPlayerByElement");return a?a("player-api"):null};
var Mf=function(){var a=m.C("player"),b=m.Nf();if(a&&b){var a=a&&m.y(a,"off-screen"),b=1==(b&&b.isReady()?b.getPlayerState():void 0),c="watch"==m.s("PAGE_NAME");Rf&&!Jf&&b&&Pf("minimized PP playing");a&&c?Pf("PP off-screen on watch"):Jf||a||c||Pf("PP !off-screen off watch")}};var Of=function(){if(Jf){var a="watch"==m.s("PAGE_NAME"),b=m.Nf();1==(b&&b.isReady()?b.getPlayerState():void 0)?Sf(!0):a&&Sf(!1);Tf()}};
var Tf=function(){var a=m.C("player"),b=m.C("player-mole-container");Rf=!a||m.y(a,"off-screen")||!b||m.y(b,"watch-mole");(a=m.Nf())&&a.isReady()&&a.setMinimized(Rf)};var Pf=function(a){var b=m.s("PAGE_NAME");b&&(b=[b,Qf,m.k("_spf_state.nav-counter")],a+="("+b.join(",")+")",m.h("yt.www.persistentplayer.issue",a,void 0),m.Xa(Error(a),"WARNING"))};var Sf=function(a){m.lb(m.C("player-mole-container"),"video-mole",a);Tf()};
var Uf=function(){m.fc("ol");Vf("init");var a=m.s("PAGE_NAME");a&&Vf("init-"+a);wc()};var Vf=function(a){m.xc()?Wf.push(m.zc(m.p(m.hb,a),0)):m.x(a)};var Xf=function(){m.Cc(Wf);Wf.length=0;var a=m.s("PAGE_NAME");a&&m.hb("dispose-"+a);m.hb("dispose")};var cba=function(){Uf()};var dba=function(){m.s("TIMING_REPORT_ON_UNLOAD")&&vc(!0);m.s("EXP_DEFER_CSI_PING")&&sc("u");Xf()};
var eba=function(a,b,c,d,f){for(var g=window.document.getElementsByTagName("script"),n=!1,q=0,t=g.length;q<t;q++)if(0<g[q].src.indexOf("/debug-")){n=!0;break}n&&(f||(f=Error(),f.message=a,f.fileName=b,f.lineNumber=c,(0,window.isNaN)(d)||(f.columnNumber=d)),m.Xa(f))};var Yf=function(){Zf=1;$f=0;m.s("TIMING_REPORT_ON_UNLOAD")&&vc(!0);m.s("EXP_DEFER_CSI_PING")&&sc("n");oc(void 0);pc();m.s("CSI_TRACK_ON_BEGIN")&&ic("nb");hc("mark_navigation_requested");ag(fba);m.hb("navigate")};
var bg=function(a){a=a.detail.part||a.detail.partial;m.fc("nc"+$f);++$f;var b=1==Zf;Zf=2;b?(ag(gba),cg()):ag(hba);(a=a.data&&a.data.swfcfg)&&dg(a)};var eg=function(){};var fg=function(a){a=a.detail.response;var b=1==Zf;Zf=3;b&&(ag(iba),cg());(a=a.data&&a.data.swfcfg)&&dg(a)};
var gg=function(a){m.fc("nd");a=a.detail.response.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;jc(void 0).yt_nav=b;ic("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);jc(void 0).srt=b;b=a.spfCached?"hot":"warm";jc(void 0).yt_lt=b;b=+!!a.spfPrefetched;jc(void 0).yt_pft=b;kc("req",a.responseStart-a.fetchStart);ag(hg);window.document.getElementById("content").style.height="";Uf();Zf=0};
var ig=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),m.Xa(a)};var jg=function(a){a=m.bc({spfreload:"1",url:a.detail.url,reason:a.detail.reason});m.$c(a)};var jba=function(){kba()};var lba=function(){};
var cg=function(){window.scroll(0,0);var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Xf();for(var b in m.Sa)delete m.Sa[b];m.h("ytplayer.config",null,void 0);if(!Jf)if((a=m.Nf())&&a.stopVideo){if(a.stopVideo(),a=a.getLastError())Qf=a,(a=m.C("movie_player"))&&a.stopVideo?(a.stopVideo(),Qf="recovered"):Qf="missing2"}else Qf="missing";Mf()};var dg=function(a){"cfg"in gc(void 0)||m.fc("cfg");Kf(a)};
var ag=function(a){function b(){var b=a[0],f=a[1],g=a[2];c.className="";var n=c.style;n.transitionDuration=n.webkitTransitionDuration=b+"ms";n.width=f+"%";m.Va(kg);kg=m.u(function(){c.className=g},b)}var c=window.document.getElementById("progress");c||(c=window.document.createElement("div"),c.id="progress",c.innerHTML="<dt><dd>",window.document.body.appendChild(c));m.yc()?(m.Bc(lg),lg=m.zc(b,0)):(m.Va(kg),kg=m.u(b,0))};
var kba=function(){var a=hg[0]+50;m.Va(kg);kg=m.u(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
var mba=function(){"watch"!=m.s("PAGE_NAME")&&m.h("yt.www.skywatch.lastBrowsePage",window.location.href,void 0);if(m.s("SKYWATCH_ENABLED")){var a=m.C("skywatch-close-button");a||(a=window.document.createElement("button"),m.jb(a,["yt-uix-button","yt-uix-button-default"]),a.id="skywatch-minimize-button",a.innerHTML="\u21f2",m.C("player-mole-container").appendChild(a));mg.push(m.G(a,"click",nba))}};var nba=function(){m.td(m.k("yt.www.skywatch.lastBrowsePage")||"/")};
var ng=function(){m.Dc.call(this,"www/base");this.j=0};var og=function(a){(a=a.detail.name)&&Hc(a)};m.ba=[];m.pg=m.pg||{};m.ea=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;m.E=Date.now||function(){return+new Date};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.l.apply(null,c)}return(0,m.l)(this,a)};m.qa[" "]=m.fa;m.r(m.ra,Error);m.ra.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;m.xa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;m.Ha=Array.prototype;m.Ea=m.Ha.indexOf?function(a,b,c){return m.Ha.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(m.ka(a))return m.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
m.oba=m.Ha.lastIndexOf?function(a,b,c){return m.Ha.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(m.ka(a))return m.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};m.w=m.Ha.forEach?function(a,b,c){m.Ha.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=m.ka(a)?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)};
m.kb=m.Ha.filter?function(a,b,c){return m.Ha.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],g=0,n=m.ka(a)?a.split(""):a,q=0;q<d;q++)if(q in n){var t=n[q];b.call(c,t,q,a)&&(f[g++]=t)}return f};m.qg=m.Ha.map?function(a,b,c){return m.Ha.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=Array(d),g=m.ka(a)?a.split(""):a,n=0;n<d;n++)n in g&&(f[n]=b.call(c,g[n],n,a));return f};
m.rg=m.Ha.reduce?function(a,b,c,d){d&&(b=(0,m.l)(b,d));return m.Ha.reduce.call(a,b,c)}:function(a,b,c,d){var f=c;(0,m.w)(a,function(c,n){f=b.call(d,f,c,n,a)});return f};m.sg=m.Ha.some?function(a,b,c){return m.Ha.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=m.ka(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return!0;return!1};
m.tg=m.Ha.every?function(a,b,c){return m.Ha.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=m.ka(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&!b.call(c,f[g],g,a))return!1;return!0};m.Ka.prototype.ob=!1;m.Ka.prototype.ga=function(){return this.ob};m.Ka.prototype.dispose=function(){this.ob||(this.ob=!0,this.M())};m.Ka.prototype.M=function(){if(this.ua)for(;this.ua.length;)this.ua.shift()()};m.r(m.Oa,m.Ka);m.e=m.Oa.prototype;m.e.Dn=1;m.e.Vg=0;m.e.subscribe=function(a,b,c){var d=this.Cb[a];d||(d=this.Cb[a]=[]);var f=this.Dn;this.oa[f]=a;this.oa[f+1]=b;this.oa[f+2]=c;this.Dn=f+3;d.push(f);return f};m.e.unsubscribe=function(a,b,c){if(a=this.Cb[a]){var d=this.oa;if(a=m.Ba(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.wb(a)}return!1};
m.e.wb=function(a){if(0!=this.Vg)return this.j||(this.j=[]),this.j.push(a),!1;var b=this.oa[a];if(b){var c=this.Cb[b];c&&m.Fa(c,a);delete this.oa[a];delete this.oa[a+1];delete this.oa[a+2]}return!!b};m.e.publish=function(a,b){var c=this.Cb[a];if(c){this.Vg++;for(var d=m.Ja(arguments,1),f=0,g=c.length;f<g;f++){var n=c[f];this.oa[n+1].apply(this.oa[n+2],d)}this.Vg--;if(this.j&&0==this.Vg)for(;c=this.j.pop();)this.wb(c);return 0!=f}return!1};
m.e.clear=function(a){if(a){var b=this.Cb[a];b&&((0,m.w)(b,this.wb,this),delete this.Cb[a])}else this.oa.length=0,this.Cb={}};m.e.na=m.aa(3);m.e.M=function(){m.Oa.L.M.call(this);delete this.oa;delete this.Cb;delete this.j};m.Sa=window.yt&&window.yt.config_||{};m.h("yt.config_",m.Sa,void 0);m.h("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);m.Za=window.yt&&window.yt.msgs_||{};m.h("yt.msgs_",m.Za,void 0);m.Ud="Microsoft Internet Explorer"==window.navigator.appName;var pba=m.k("yt.pubsub.instance_")||new m.Oa;m.Oa.prototype.subscribe=m.Oa.prototype.subscribe;m.Oa.prototype.unsubscribeByKey=m.Oa.prototype.wb;m.Oa.prototype.publish=m.Oa.prototype.publish;m.Oa.prototype.clear=m.Oa.prototype.clear;m.h("yt.pubsub.instance_",pba,void 0);var db=m.k("yt.pubsub.subscribedKeys_")||{};m.h("yt.pubsub.subscribedKeys_",db,void 0);var fb=m.k("yt.pubsub.topicToKeys_")||{};m.h("yt.pubsub.topicToKeys_",fb,void 0);var eb=m.k("yt.pubsub.isSynchronous_")||{};
m.h("yt.pubsub.isSynchronous_",eb,void 0);m.cb=m.k("yt.pubsub.skipSubId_")||null;m.h("yt.pubsub.skipSubId_",m.cb,void 0);var sb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");e:{var ug=m.ea.navigator;if(ug){var vg=ug.userAgent;if(vg){m.wd=vg;break e}}m.wd=""};var Eg,xb,wb,Fg;m.be=m.va(m.wd,"Opera")||m.va(m.wd,"OPR");m.zb=m.va(m.wd,"Trident")||m.va(m.wd,"MSIE");m.ae=m.va(m.wd,"Gecko")&&!m.va(m.wd.toLowerCase(),"webkit")&&!(m.va(m.wd,"Trident")||m.va(m.wd,"MSIE"));m.$d=m.va(m.wd.toLowerCase(),"webkit");m.$d&&m.va(m.wd,"Mobile");var Ag=m.ea.navigator||null,Cg=Ag&&Ag.platform||"";m.Yd=m.va(Cg,"Mac");m.Xd=m.va(Cg,"Win");m.wg=m.va(Cg,"Linux");var Dg=m.wd;m.xg=!!Dg&&m.va(Dg,"Android");m.yg=!!Dg&&m.va(Dg,"iPhone");m.zg=!!Dg&&m.va(Dg,"iPad");
Eg=m.ea.navigator||null;m.qba=!!Eg&&m.va(Eg.appVersion||"","X11");xb=function(){var a="",b;if(m.be&&m.ea.opera)return a=m.ea.opera.version,m.ma(a)?a():a;m.ae?b=/rv\:([^\);]+)(\)|;)/:m.zb?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:m.$d&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(m.wd))?a[1]:"");return m.zb&&(b=ub(),b>(0,window.parseFloat)(a))?String(b):a}();wb={};Fg=m.ea.document;m.Ab=Fg&&m.zb?ub()||("CSS1Compat"==Fg.compatMode?(0,window.parseInt)(xb,10):5):void 0;var kaa;kaa=!m.zb||m.yb(9);m.rba=!m.ae&&!m.zb||m.zb&&m.yb(9)||m.ae&&m.vb("1.9.1");m.Gg=m.zb&&!m.vb("9");m.sba=m.zb||m.be||m.$d;var Eb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.Pb="StopIteration"in m.ea?m.ea.StopIteration:Error("StopIteration");m.Nb.prototype.next=function(){throw m.Pb;};m.Nb.prototype.Jb=function(){return this};var oaa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,Ub=m.$d;var Yaa=/^https?:\/\/([A-Za-z0-9-]{1,63}\.)*(corp\.google\.com|borg\.google\.com|prod\.google\.com|video\.google\.com|youtube\.com|youtube\.googleapis\.com|youtube-nocookie\.com|youtubeeducation\.com)(:[0-9]+)?\/embed\//;var ec={},qaa=0,tba=m.k("yt.net.ping.workerUrl_")||null;m.h("yt.net.ping.workerUrl_",tba,void 0);var rc,tc,uc;var qc=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},pc=(0,m.l)(qc.clearResourceTimings||qc.webkitClearResourceTimings||qc.mozClearResourceTimings||qc.msClearResourceTimings||qc.oClearResourceTimings||m.fa,qc),hc=qc.mark?function(a){qc.mark(a)}:m.fa;m.e=m.Dc.prototype;m.e.iv=function(){2==this.A||this.init()};m.e.enable=function(){this.A=1;(0,m.w)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.iv,this),this.subscribe("dispose-"+a,this.dispose,this),m.s("PAGE_NAME")==a&&m.Ec(this))},this)};m.e.init=function(){this.A=2;this.F&&this.F()};m.e.dispose=function(){this.A=3;m.Bc(this.B);this.C&&this.C()};m.e.disable=function(){this.A=4;this.dispose();this.clear()};
m.e.subscribe=function(a,b,c){a=m.v(a,b,c);this.oa.push(a);return a};m.e.clear=function(){m.gb(this.oa);this.oa=[]};var Gc=m.k("yt.modules.registry_")||{};m.h("yt.modules.registry_",Gc,void 0);m.Hg=null;"undefined"!=typeof window.XMLHttpRequest?m.Hg=function(){return new window.XMLHttpRequest}:"undefined"!=typeof window.ActiveXObject&&(m.Hg=function(){return new window.ActiveXObject("Microsoft.XMLHTTP")});var Jc,Kc,Lc,Mc,Pc,Rc=0,Qc=0,Oc=[],vaa=/.+\.googlevideo\.com|c\.youtube\.com|\/videoplayback\?|spf\=navigate/g;var Uc={};var xaa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,yaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;m.Zc=m.Vb;var Aaa={enablejsapi:1},Baa={},Caa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};ad.prototype.clone=function(){var a=new ad,b;for(b in this){var c=this[b];"object"==m.ha(c)?a[b]=m.qb(c):a[b]=c}return a};m.ed=/\s*;\s*/;m.e=m.cd.prototype;m.e.set=function(a,b,c,d,f,g){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');m.da(c)||(c=-1);f=f?";domain="+f:"";d=d?";path="+d:"";g=g?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.E)()+1E3*c)).toUTCString();this.j.cookie=a+"="+b+f+d+c+g};
m.e.get=function(a,b){for(var c=a+"=",d=(this.j.cookie||"").split(m.ed),f=0,g;g=d[f];f++){if(0==g.lastIndexOf(c,0))return g.substr(c.length);if(g==a)return""}return b};m.e.remove=function(a,b,c){var d=m.da(this.get(a));this.set(a,"",0,b,c);return d};m.e.Qa=m.aa(4);m.e.ra=m.aa(5);m.e.isEmpty=m.aa(6);m.e.na=m.aa(2);m.e.Ne=m.aa(7);m.e.clear=function(){for(var a=m.dd(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.gd=new m.cd(window.document);m.gd.A=3950;m.uba=m.$d?"webkit":m.ae?"moz":m.zb?"ms":m.be?"o":"";m.Ig=m.k("yt.dom.getNextId_");if(!m.Ig){m.Ig=function(){return++vba};m.h("yt.dom.getNextId_",m.Ig,void 0);var vba=0};m.e=m.jd.prototype;m.e.wa=null;m.e.type="";m.e.target=null;m.e.relatedTarget=null;m.e.currentTarget=null;m.e.data=null;m.e.source=null;m.e.state=null;m.e.keyCode=0;m.e.charCode=0;m.e.altKey=!1;m.e.ctrlKey=!1;m.e.shiftKey=!1;m.e.clientX=0;m.e.clientY=0;m.e.wheelDeltaX=0;m.e.wheelDeltaY=0;m.e.rotation=0;m.e.scale=1;m.e.changedTouches=null;m.e.preventDefault=m.aa(8);m.e.stopPropagation=m.aa(9);m.e.stopImmediatePropagation=m.aa(10);
var Daa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.ld=m.k("yt.events.listeners_")||{};m.h("yt.events.listeners_",m.ld,void 0);var md=m.k("yt.events.counter_")||{count:0};m.h("yt.events.counter_",md,void 0);var Cd;var yd,zd=!1,Ad=[];m.Fd.prototype.then=function(a,b,c){return m.Ld(this,m.ma(a)?a:null,m.ma(b)?b:null,c)};m.Dd(m.Fd);m.Fd.prototype.cancel=function(a){0==this.A&&xd(function(){var b=new Md(a);Id(this,b)},this)};m.Fd.prototype.H=function(a){this.A=0;Gd(this,2,a)};m.Fd.prototype.K=function(a){this.A=0;Gd(this,3,a)};m.Fd.prototype.J=function(){for(;this.j&&this.j.length;){var a=this.j;this.j=[];for(var b=0;b<a.length;b++)Jd(this,a[b],this.A,this.G)}this.F=!1};var Kaa=vd;m.r(Md,m.ra);Md.prototype.name="cancel";var Pd=null;Nd.prototype.C=function(a){Qd(this,"startFeedback",arguments)};Nd.prototype.F=function(a){Qd(this,"startHelp",arguments)};Nd.prototype.j=function(a){Qd(this,"loadChatSupport",arguments)};var Jg=!1,Kg="";
if(window.navigator.plugins&&window.navigator.plugins.length){var Lg=window.navigator.plugins["Shockwave Flash"];Lg&&(Jg=!0,Lg.description&&(Kg=Rd(Lg.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(Jg=!0,Kg="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var Mg=window.navigator.mimeTypes["application/x-shockwave-flash"];(Jg=Mg&&Mg.enabledPlugin)&&(Kg=Rd(Mg.enabledPlugin.description))}else try{var Ng=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),Jg=
!0,Kg=Rd(Ng.GetVariable("$version"))}catch(wba){try{Ng=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),Jg=!0,Kg="6.0.21"}catch(xba){try{Ng=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),Jg=!0,Kg=Rd(Ng.GetVariable("$version"))}catch(yba){}}}m.zba=Jg;m.Og=Kg;var Pg,Qg,Rg,Sg,Tg,Ug,Vg,Aba,Bba,Cba,Dba;Vg=Ug=Tg=Sg=Rg=Qg=Pg=!1;var Wg=m.wd;Wg&&(-1!=Wg.indexOf("Firefox")?Pg=!0:-1!=Wg.indexOf("Camino")?Qg=!0:-1!=Wg.indexOf("iPhone")||-1!=Wg.indexOf("iPod")?Rg=!0:-1!=Wg.indexOf("iPad")?Sg=!0:-1!=Wg.indexOf("Chrome")?Ug=!0:-1!=Wg.indexOf("Android")?Tg=!0:-1!=Wg.indexOf("Safari")&&(Vg=!0));m.Xg=Pg;Aba=Qg;Bba=Rg;Cba=Sg;Dba=Tg;m.Yg=Ug;m.Zg=Vg;m.$g=function(){if(m.Xg)return Sd(/Firefox\/([0-9.]+)/);if(m.zb||m.be)return xb;if(m.Yg)return Sd(/Chrome\/([0-9.]+)/);if(m.Zg)return Sd(/Version\/([0-9.]+)/);if(Bba||Cba){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.wd))return a[1]+"."+a[2]}else{if(Dba)return(a=Sd(/Android\s+([0-9.]+)/))?a:Sd(/Version\/([0-9.]+)/);if(Aba)return Sd(/Camino\/([0-9.]+)/)}return""}();m.ga(Td);Td.prototype.getVersion=function(){return[this.j,this.A,this.B]};m.e=m.de.prototype;m.e.clone=function(){return new m.de(this.top,this.right,this.bottom,this.left)};m.e.contains=function(a){return m.ee(this,a)};m.e.ceil=m.aa(11);m.e.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.e.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
m.e.scale=function(a,b){var c=m.la(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Raa=tb("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));m.Eba=RegExp("^[^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");m.Fba=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");m.ie.prototype.yh=!0;m.ie.prototype.xh=function(){return this.j};m.ie.prototype.toString=function(){return"Const{"+this.j+"}"};var je={};le.prototype.yh=!0;var me={};le.prototype.xh=function(){return this.j};var Paa=ne(""),Oaa=/^[-.%_!# a-zA-Z0-9]+$/;oe.prototype.yh=!0;oe.prototype.xh=function(){return""};oe.prototype.On=!0;oe.prototype.Hg=function(){return 1};var pe={};var ue,Qaa,Naa,re;qe.prototype.On=!0;qe.prototype.Hg=function(){return this.A};qe.prototype.yh=!0;qe.prototype.xh=function(){return this.j};ue=/^[a-zA-Z0-9-]+$/;Qaa=tb("action","cite","data","formaction","href","manifest","poster","src");Naa=tb("link","script","style");re={};m.ah=ve("",0);m.bh=m.Mb(function(){if(m.zb)return m.vb("10.0");var a=window.document.createElement("div"),b=m.ce(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b=m.te("div",{style:c});a.innerHTML=m.se(b);a=a.firstChild;b=a.style[m.za("transition")];return""!=("undefined"!==typeof b?b:a.style[m.fe(a,"transition")]||"")});var Ce;m.ye={};Ce=!1;m.ga(m.Ee);m.Fe=m.k("yt.prefs.UserPrefs.prefs_")||{};m.h("yt.prefs.UserPrefs.prefs_",m.Fe,void 0);m.e=m.Ee.prototype;m.e.get=function(a,b){He(a);Ge(a);var c=void 0!==m.Fe[a]?m.Fe[a].toString():null;return null!=c?c:b?b:""};m.e.set=function(a,b){He(a);Ge(a);if(null==b)throw"ExpectedNotNull";m.Fe[a]=b.toString()};m.e.remove=function(a){He(a);Ge(a);delete m.Fe[a]};m.e.save=function(){var a;a=[];for(var b in m.Fe)a.push(b+"="+(0,window.escape)(m.Fe[b]));a=a.join("&");m.fd("PREF",a,63072E3)};
m.e.clear=function(){m.Fe={}};var Uaa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Se;var ch=m.wd,ch=ch.toLowerCase();if(m.va(ch,"android")){var dh=ch.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(dh)Se=Number(dh[1]);else{var eh={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},fh=ch.match("("+m.ob(eh).join("|")+")");Se=fh?eh[fh[0]]:0}}else Se=void 0;m.r(m.Te,Waa);m.Te.prototype.na=m.aa(1);m.Te.prototype.clear=function(){var a=m.Rb(this.Jb(!0)),b=this;(0,m.w)(a,function(a){b.remove(a)})};m.r(m.Ue,m.Te);m.e=m.Ue.prototype;m.e.isAvailable=function(){if(!this.j)return!1;try{return this.j.setItem("__sak","1"),this.j.removeItem("__sak"),!0}catch(a){return!1}};m.e.set=function(a,b){try{this.j.setItem(a,b)}catch(c){if(0==this.j.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.e.get=function(a){a=this.j.getItem(a);if(!m.ka(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.e.remove=function(a){this.j.removeItem(a)};
m.e.na=m.aa(0);m.e.Jb=function(a){var b=0,c=this.j,d=new m.Nb;d.next=function(){if(b>=c.length)throw m.Pb;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!m.ka(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.e.clear=function(){this.j.clear()};m.e.key=function(a){return this.j.key(a)};m.r(m.Ve,m.Ue);m.r(We,m.Ue);var cf={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Xaa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.df.prototype.set=function(a,b){m.da(b)?this.j.set(a,m.Ye(b)):this.j.remove(a)};m.df.prototype.get=function(a){var b;try{b=this.j.get(a)}catch(c){return}if(null!==b)try{return m.Xe(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.df.prototype.remove=function(a){this.j.remove(a)};m.r(ef,m.df);ef.prototype.set=function(a,b){ef.L.set.call(this,a,gf(b))};ef.prototype.A=function(a){a=ef.L.get.call(this,a);if(!m.da(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};ef.prototype.get=function(a){if(a=this.A(a)){if(a=a.data,!m.da(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};m.r(hf,ef);hf.prototype.set=function(a,b,c){if(b=gf(b)){if(c){if(c<(0,m.E)()){hf.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.E)()}hf.L.set.call(this,a,b)};hf.prototype.A=function(a,b){var c=hf.L.A.call(this,a);if(c)if(!b&&m.jf(c))hf.prototype.remove.call(this,a);else return c};m.r(m.kf,hf);var gh,hh;gh=new m.Ve;m.mf=gh.isAvailable()?new m.kf(gh):null;hh=new We;m.nf=hh.isAvailable()?new m.kf(hh):null;m.r(qf,m.Ka);m.e=qf.prototype;m.e.getId=function(){return this.R};m.e.vi=function(a,b){this.ga()||(sf(this,a),yf(this,b),this.G&&uf(this))};m.e.Mr=function(){return this.pa};
m.e.ew=function(){if(!this.T){var a=!0;this.Ia&&(a=zf(this));a&&"html5"==Bf(this)?(this.F="html5",this.G||this.le()):(Cf(this),this.F="html5",a&&this.la?(this.$c.appendChild(this.la),this.le()):(this.ca.loaded=!0,this.H=(0,m.l)(function(){var a=this.$c,c=this.ca.clone();m.k("yt.player.Application.create")(a,c);this.le()},this),this.T=!0,zf(this)?this.H():(m.Vc(this.ca.assets.js,this.H),m.Re(this.ca.assets.css))))}};
m.e.dw=function(){var a=this.ca.clone();a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Bf(this)?(this.F="flash",this.G||Qe(a,!1,(0,m.l)(this.le,this))):(Cf(this),this.F="flash",this.ca.loaded=!0,m.Me(this.$c,a),this.le())};
m.e.le=function(){var a=xf(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(c){}if(b)if(this.T=!1,a.isNotServable&&a.isNotServable())wf(this);else{rf(this);this.G=!0;a=xf(this);a.addEventListener&&(this.J=Af(this,a,"addEventListener"));a.removeEventListener&&(this.W=Af(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),d=0;d<b.length;d++){var f=b[d];this.j[f]||(this.j[f]=Af(this,a,f))}for(var g in this.C)this.J(g,this.C[g]);uf(this);
this.$&&this.$(this.j);this.P.publish("onReady",this.j)}else this.Ma=m.u((0,m.l)(this.le,this),50)};m.e.Qr=function(){return this.G};m.e.Vd=function(a,b){if(!this.ga()){var c=tf(this,b);if(c){if(!m.Da(this.Ua,a)&&!this.C[a]){var d=$aa(this,a);this.J&&this.J(a,d)}this.P.subscribe(a,c);"onReady"==a&&this.G&&m.u(m.p(c,this.j),0)}}};m.e.Pr=function(a,b){if(!this.ga()){var c=tf(this,b);c&&this.P.unsubscribe(a,c)}};
m.e.Bo=function(a){a=a?naa:maa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.e.Do=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?pf().volume:m.mb(a.volume,0,100);b.muted=void 0==a.muted?pf().muted:a.muted;m.lf("yt-player-volume",b,2592E3)};m.e.Co=function(a){5==a&&wf(this)};m.e.Eo=function(a){m.x("WATCH_LATER_VIDEO_ADDED",a)};m.e.Fo=function(a){m.x("WATCH_LATER_VIDEO_REMOVED",a)};
m.e.gw=function(){Cf(this);this.F="unsupported";var a=this.ca.messages.player_fallback||'Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a=this.ca.messages.quicktime_fallback||'Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=m.C("player-unavailable");m.C("unavailable-submessage")&&b&&(m.C("unavailable-submessage").innerHTML=a,(a=m.D("icon",b))&&m.Tc(a,"icon")&&(a.src=m.F(a,"icon")),m.B(b,"hid"),m.A(m.C("player"),"off-screen-trigger"))};m.e.Or=function(){return this.F||Bf(this)};m.e.Nr=function(){return this.Ea};m.e.cancel=function(){this.H&&m.Xc(this.ca.assets.js,this.H);m.Va(this.Ma);this.T=!1};m.e.Kt=function(){var a=m.k("yt.player.ui.shared.init");a&&(this.j.hideUserInterface(),a(this.A,this.ca.clone()))};
m.e.M=function(){Cf(this);if(this.K){var a=m.k("yt.player.ui.shared.dispose");a&&a();this.za=!1}this.fa=null;for(var b in this.C)m.ea[this.C[b]]=null;this.j=null;delete this.$c;delete this.A;this.ca&&(this.pa=this.ca=this.ca.fallback=null);qf.L.M.call(this)};var Ff={},Ef="player_uid_"+(1E9*Math.random()>>>0);var Gba=m.k("yt.player.exports.navigate")||m.ud;m.h("yt.player.exports.navigate",Gba,void 0);var Hba=m.k("yt.player.embed")||m.Df;m.h("yt.player.embed",Hba,void 0);var Iba=m.k("yt.player.destroy")||m.Hf;m.h("yt.player.destroy",Iba,void 0);var Jba=m.k("yt.player.cancelAll")||Gf;m.h("yt.player.cancelAll",Jba,void 0);var Kba=m.k("yt.player.getPlayerByElement")||m.If;m.h("yt.player.getPlayerByElement",Kba,void 0);var Lba=m.k("yt.player.exports.feedbackStart")||m.Ae;
m.h("yt.player.exports.feedbackStart",Lba,void 0);var Mba=m.k("yt.player.exports.feedbackShowArticle")||m.De;m.h("yt.player.exports.feedbackShowArticle",Mba,void 0);var Nba=m.k("yt.util.activity.init")||m.nd;m.h("yt.util.activity.init",Nba,void 0);var Oba=m.k("yt.util.activity.getTimeSinceActive")||m.pd;m.h("yt.util.activity.getTimeSinceActive",Oba,void 0);var Pba=m.k("yt.util.activity.setTimestamp")||od;m.h("yt.util.activity.setTimestamp",Pba,void 0);var Lf,Rf=!1,Qf="",Jf=!1;var Wf=[];var Zf,kg,lg,$f=0,fba=[900,60,"waiting"],iba=[500,99,"waiting"],gba=[300,60,"waiting"],hba=[400,99,"waiting"],hg=[300,101,"done"];var mg=[];window.yt=window.yt||{};m.h("yt.setConfig",m.Qa,void 0);m.h("yt.getConfig",m.s,void 0);m.h("yt.hasMsg",m.$a,void 0);m.h("yt.pubsub.publish",m.x,void 0);m.h("yt.pubsub.subscribe",m.v,void 0);m.h("yt.setMsg",m.Ya,void 0);m.h("yt.setGoogMsg",function(a){Ra(m.Za,arguments)},void 0);m.h("yt.setAjaxToken",function(){},void 0);m.h("reportTimingMaps",function(a,b,c,d){if(a)for(var f in a)m.fc(f,a[f],d);if(c)for(var g in c)kc(g,c[g],d);if(b)for(var n in b)a=n,c=b[n],jc(d)[a]=c;return wc(d)},void 0);
m.h("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],f;for(f in a)"_"!=f.charAt(0)&&d.push(f+"."+a[f]);c.rt=d.join(",");for(var g in b)"_"!=g.charAt(0)&&(c[g]=b[g]);a=m.s("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);nc(c)},void 0);m.r(ng,m.Dc);
ng.prototype.enable=function(){window.onload=cba;window.onunload=dba;window.onerror=eba;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",Yf),window.addEventListener("spfpartprocess",bg),window.addEventListener("spfpartdone",eg),window.addEventListener("spfprocess",fg),window.addEventListener("spfdone",gg),window.addEventListener("spferror",ig),window.addEventListener("spfreload",jg),window.addEventListener("spfjsbeforeunload",og)),a.config=a.config||
{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",jba),this.subscribe("dispose",lba)):window.spf.dispose();this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
ng.prototype.init=function(){ng.L.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();raa();var a=window.ytPageFrameLoaded||!1,b,c;!a&&m.s("PAGEFRAME_JS")?(b=m.s("PAGEFRAME_JS"),c=function(){m.k("ytbin.www.pageframe.setup")();window.ytPageFrameLoaded=!0}):a&&(a=m.k("yt.www.masthead.loadSearchbox"))&&a();var a=m.s("JS_COMMON_MODULE"),d=m.s("JS_PAGE_MODULES");if(window.ytdepmap)d||(d=[a]),a=m.s("JS_DELAY_LOAD",void 0),0<a?(m.Va(this.j),this.j=m.u(function(){b&&m.Vc(b,c);window.spf.script.require(d)},
a)):(b&&m.Vc(b,c),window.spf.script.require(d));else{var f={};f[a]=d;a=m.s("JS_DELAY_LOAD",void 0);0<a?(m.Va(this.j),this.j=m.u(function(){b&&m.Vc(b,c);m.Yc(f)},a)):(b&&m.Vc(b,c),m.Yc(f))}mba();bba();var a=!!m.k("yt.reactLoaded"),g=m.s("REACT_JS");!a&&g&&m.Vc(g,function(){m.h("yt.reactLoaded",!0,void 0)})};
ng.prototype.dispose=function(){m.Va(this.j);var a=m.k("ytbin.www.pageframe.cancelSetup");a&&a();m.I(mg);mg.length=0;m.Wa(Lf);if(a=m.Nf())a.removeEventListener("onReady",Mf),a.removeEventListener("onStateChange",Mf),a.removeEventListener("onReady",Of),a.removeEventListener("onStateChange",Of);ng.L.dispose.call(this)};
ng.prototype.disable=function(){ng.L.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",Yf),window.removeEventListener("spfpartprocess",bg),window.removeEventListener("spfpartdone",eg),window.removeEventListener("spfprocess",fg),window.removeEventListener("spfdone",gg),window.removeEventListener("spferror",ig),window.removeEventListener("spfreload",jg),window.removeEventListener("spfjsbeforeunload",og));window.onload=null;window.onunload=null;window.onerror=null};
m.Fc(new ng);})(_yt_www);
